-- =============================================================================
-- 006_llm_invocation_log_and_capture_config.sql
--
-- Feature: tela admin de inspeção de prompts LLM.
--
--   (1) Singleton aihub.llm_capture_config — admin liga/desliga captura via UI.
--       Scope opcional por projeto/agent/workflow. TTL via ExpiresAt + hosted
--       service que zera Enabled quando vence.
--
--   (2) aihub.llm_invocation_log — captura request + response do LLM por turno
--       (1 row por TurnId+AttemptIndex). Particionada mensalmente pro TTL de
--       30d (DROP PARTITION em hosted service — mais barato que DELETE).
--       Cap de 256KB por payload via CHECK constraint (mais o app trunca antes).
--
--   (3) ALTER aihub.llm_token_usage adicionando TurnId UUID nullable —
--       permite JOIN com llm_invocation_log via TurnId (correlação 1:1
--       quando captura está ON).
--
-- Idempotente: IF NOT EXISTS / ON CONFLICT em todos os passos. Particionamento
-- usa range mensal; partições são pré-criadas pra "este mês" + "próximo mês"
-- aqui; demais ficam por conta do hosted service de retention que também cria
-- a próxima partição quando dropa a antiga.
-- =============================================================================

BEGIN;

-- ─── (1) llm_capture_config (singleton) ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS aihub.llm_capture_config (
    "Id"          SMALLINT     NOT NULL DEFAULT 1,
    "Enabled"     BOOLEAN      NOT NULL DEFAULT FALSE,
    "ProjectIds"  JSONB        NULL,
    "AgentIds"    JSONB        NULL,
    "WorkflowIds" JSONB        NULL,
    "ExpiresAt"   TIMESTAMPTZ  NULL,
    "EnabledBy"   VARCHAR(128) NULL,
    "EnabledAt"   TIMESTAMPTZ  NULL,
    "UpdatedAt"   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT "PK_llm_capture_config" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_llm_capture_config_singleton" CHECK ("Id" = 1)
);

INSERT INTO aihub.llm_capture_config ("Id", "Enabled")
VALUES (1, FALSE)
ON CONFLICT ("Id") DO NOTHING;

-- ─── (2) llm_invocation_log (particionada por CreatedAt) ────────────────────
CREATE TABLE IF NOT EXISTS aihub.llm_invocation_log (
    "Id"                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "TurnId"              UUID         NOT NULL,
    "AttemptIndex"        SMALLINT     NOT NULL DEFAULT 0,
    "ExecutionId"         VARCHAR(128) NULL,
    "WorkflowId"          VARCHAR(256) NULL,
    "AgentId"             VARCHAR(256) NOT NULL,
    "AgentVersionId"      VARCHAR(64)  NULL,
    "StepIndex"           INTEGER      NULL,
    "ProjectId"           VARCHAR(128) NULL,
    "Provider"            VARCHAR(64)  NOT NULL,
    "ProviderResolved"    VARCHAR(64)  NOT NULL,
    "Model"               VARCHAR(256) NOT NULL,
    "Intent"              VARCHAR(128) NULL,
    "RequestPayload"      JSONB        NOT NULL,
    "ResponsePayload"     JSONB        NOT NULL,
    "Composition"         JSONB        NULL,
    "ChatOptionsSnapshot" JSONB        NULL,
    "Status"              VARCHAR(24)  NOT NULL,
    "ErrorMessage"        TEXT         NULL,
    "DurationMs"          DOUBLE PRECISION NOT NULL,
    "InputTokens"         INTEGER      NOT NULL DEFAULT 0,
    "OutputTokens"        INTEGER      NOT NULL DEFAULT 0,
    "CachedTokens"        INTEGER      NOT NULL DEFAULT 0,
    "RequestSizeBytes"    INTEGER      NOT NULL,
    "ResponseSizeBytes"   INTEGER      NOT NULL,
    "Truncated"           BOOLEAN      NOT NULL DEFAULT FALSE,
    "CreatedAt"           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT "PK_llm_invocation_log" PRIMARY KEY ("Id", "CreatedAt"),
    -- 256KB por payload. Caller já trunca antes; CHECK aqui é cinto + suspensório.
    CONSTRAINT "CK_llm_invocation_log_request_size"
        CHECK (pg_column_size("RequestPayload") <= 262144),
    CONSTRAINT "CK_llm_invocation_log_response_size"
        CHECK (pg_column_size("ResponsePayload") <= 262144)
) PARTITION BY RANGE ("CreatedAt");

-- Índices da PARENT table — propagam pras partições automaticamente.
CREATE INDEX IF NOT EXISTS "IX_llm_invocation_log_ExecutionId_CreatedAt"
    ON aihub.llm_invocation_log ("ExecutionId", "CreatedAt" DESC);
CREATE INDEX IF NOT EXISTS "IX_llm_invocation_log_AgentId_CreatedAt"
    ON aihub.llm_invocation_log ("AgentId", "CreatedAt" DESC);
CREATE INDEX IF NOT EXISTS "IX_llm_invocation_log_ProjectId_CreatedAt"
    ON aihub.llm_invocation_log ("ProjectId", "CreatedAt" DESC);
CREATE INDEX IF NOT EXISTS "IX_llm_invocation_log_TurnId"
    ON aihub.llm_invocation_log ("TurnId");
CREATE INDEX IF NOT EXISTS "IX_llm_invocation_log_Intent"
    ON aihub.llm_invocation_log ("Intent") WHERE "Intent" IS NOT NULL;

-- Pré-cria partições do mês corrente + próximo. LlmInvocationLogRetentionJob
-- cuida do resto (cria próxima quando dropa a velha).
DO $$
DECLARE
    cur_month_start DATE := date_trunc('month', NOW())::DATE;
    next_month_start DATE := (date_trunc('month', NOW()) + INTERVAL '1 month')::DATE;
    third_month_start DATE := (date_trunc('month', NOW()) + INTERVAL '2 month')::DATE;
    cur_part_name TEXT;
    next_part_name TEXT;
BEGIN
    cur_part_name := 'llm_invocation_log_' || to_char(cur_month_start, 'YYYY_MM');
    next_part_name := 'llm_invocation_log_' || to_char(next_month_start, 'YYYY_MM');

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS aihub.%I PARTITION OF aihub.llm_invocation_log FOR VALUES FROM (%L) TO (%L)',
        cur_part_name, cur_month_start, next_month_start
    );
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS aihub.%I PARTITION OF aihub.llm_invocation_log FOR VALUES FROM (%L) TO (%L)',
        next_part_name, next_month_start, third_month_start
    );
END $$;

-- ─── (3) ALTER llm_token_usage: TurnId nullable + index ─────────────────────
ALTER TABLE aihub.llm_token_usage
    ADD COLUMN IF NOT EXISTS "TurnId" UUID NULL;

CREATE INDEX IF NOT EXISTS "IX_llm_token_usage_TurnId"
    ON aihub.llm_token_usage ("TurnId") WHERE "TurnId" IS NOT NULL;

COMMIT;
