-- Migration: Document Intelligence tables
-- Data: 2026-04-17

-- ── Jobs ──────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS aihub.document_extraction_jobs (
    id                  UUID PRIMARY KEY,
    conversation_id     TEXT NOT NULL,
    user_id             TEXT NOT NULL,
    source_type         TEXT NOT NULL,
    source_ref          TEXT,
    content_sha256      TEXT NOT NULL,
    model               TEXT NOT NULL,
    features_hash       TEXT,
    status              TEXT NOT NULL DEFAULT 'created',
    operation_id        TEXT,
    result_ref          TEXT,
    page_count          INT,
    cost_usd            NUMERIC(12,6),
    error_code          TEXT,
    error_message       TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at          TIMESTAMPTZ,
    finished_at         TIMESTAMPTZ,
    duration_ms         INT,

    CONSTRAINT chk_dej_status CHECK (
        status IN ('created', 'running', 'succeeded', 'failed', 'cached')
    ),
    CONSTRAINT chk_dej_error_code CHECK (
        error_code IS NULL OR error_code IN (
            'PAGE_LIMIT_EXCEEDED',
            'UNREADABLE_PDF',
            'SOURCE_UNAVAILABLE',
            'AZURE_DI_FAILURE',
            'TIMEOUT',
            'GATE_TIMEOUT',
            'CANCELLED'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_dej_hash_model
    ON aihub.document_extraction_jobs(content_sha256, model);

CREATE INDEX IF NOT EXISTS idx_dej_conversation
    ON aihub.document_extraction_jobs(conversation_id);

CREATE INDEX IF NOT EXISTS idx_dej_status_created
    ON aihub.document_extraction_jobs(status, created_at);

-- ── Events ────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS aihub.document_extraction_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id       UUID NOT NULL REFERENCES aihub.document_extraction_jobs(id),
    event_type   TEXT NOT NULL,
    detail       JSONB,
    occurred_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_dee_job
    ON aihub.document_extraction_events(job_id, occurred_at);

-- ── Cache ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS aihub.document_extraction_cache (
    content_sha256      TEXT NOT NULL,
    model               TEXT NOT NULL,
    features_hash       TEXT NOT NULL,
    result_ref          TEXT NOT NULL,
    page_count          INT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at          TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (content_sha256, model, features_hash)
);
