-- Migration: cria aihub.admin_audit_log — trilha de auditoria de mudanças CRUD em
-- recursos administrativos (Project, Agent, Workflow, Skill, ModelPricing).
-- Idempotente (CREATE TABLE IF NOT EXISTS + CREATE INDEX IF NOT EXISTS).
--   psql -f db/migration_admin_audit_log.sql

CREATE TABLE IF NOT EXISTS aihub.admin_audit_log (
    "Id"            BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "TenantId"      VARCHAR(128) NULL,
    "ProjectId"     VARCHAR(128) NULL,
    "ActorUserId"   VARCHAR(128) NOT NULL,                 -- x-efs-account / x-efs-user-profile-id
    "ActorUserType" VARCHAR(32)  NULL,                     -- 'cliente' | 'assessor'
    "Action"        VARCHAR(32)  NOT NULL,                 -- create | update | delete
    "ResourceType"  VARCHAR(64)  NOT NULL,                 -- project | agent | workflow | skill | model_pricing
    "ResourceId"    VARCHAR(128) NOT NULL,
    "PayloadBefore" JSONB        NULL,                     -- snapshot pré-mudança (update/delete)
    "PayloadAfter"  JSONB        NULL,                     -- snapshot pós-mudança (create/update)
    "Timestamp"     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_admin_audit_log" PRIMARY KEY ("Id")
);

-- Índice principal: queries "o que mudou no tenant X nas últimas 24h" (governance dashboard).
CREATE INDEX IF NOT EXISTS "IX_admin_audit_log_TenantId_Timestamp"
    ON aihub.admin_audit_log ("TenantId", "Timestamp" DESC);

-- Índice de detalhe: navega histórico de um recurso específico ("quem mexeu no workflow X?").
CREATE INDEX IF NOT EXISTS "IX_admin_audit_log_ResourceType_ResourceId"
    ON aihub.admin_audit_log ("ResourceType", "ResourceId");

-- Índice de actor: "minhas ações administrativas" / compliance por pessoa.
CREATE INDEX IF NOT EXISTS "IX_admin_audit_log_ActorUserId_Timestamp"
    ON aihub.admin_audit_log ("ActorUserId", "Timestamp" DESC);
