-- =============================================================================
-- EfsAiHub — Schema DDL
-- PostgreSQL 16+ · Schema: aihub
--
-- Uso:
--   psql -U <usuario> -d <banco> -f schema.sql
--
-- Este arquivo é idempotente: pode ser executado múltiplas vezes sem erros.
-- Para recriar do zero, execute schema_drop.sql antes deste.
--
-- Convenções:
--   - Todas as tabelas ficam no schema aihub (não public)
--   - Timestamps sempre em UTC (TIMESTAMPTZ)
--   - PKs string usam VARCHAR com limite explícito
--   - PKs numéricas usam GENERATED BY DEFAULT AS IDENTITY
--   - JSONB para payloads semi-estruturados
--   - BYTEA para dados binários (checkpoints)
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS aihub;

SET search_path TO aihub;

-- =============================================================================
-- 1. PROJETOS (multi-tenant)
-- =============================================================================

-- Nota: projects usa colunas lowercase (sem aspas) para compatibilidade com
-- PgProjectRepository que executa raw SQL (ex: WHERE tenant_id = @tenantId).
CREATE TABLE IF NOT EXISTS aihub.projects (
    id          VARCHAR(128)  NOT NULL,
    name        VARCHAR(256)  NOT NULL,
    tenant_id   VARCHAR(128)  NOT NULL,
    description VARCHAR(1024) NULL,
    settings    JSONB         NOT NULL DEFAULT '{}',
    llm_config  JSONB         NULL,                     -- override de modelo por projeto
    budget      JSONB         NULL,                     -- limites de custo/tokens por projeto
    created_at  TIMESTAMPTZ   NOT NULL,
    updated_at  TIMESTAMPTZ   NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ix_projects_tenant_id
    ON aihub.projects (tenant_id);

-- =============================================================================
-- 2. DEFINIÇÕES DE AGENTES E WORKFLOWS
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.agent_definitions (
    "Id"                 VARCHAR(256) NOT NULL,
    "Name"               VARCHAR(512) NOT NULL,
    "Data"               TEXT         NOT NULL,                 -- JSON serializado do AgentDef
    "ProjectId"          VARCHAR(128) NOT NULL DEFAULT 'default',
    "Visibility"         VARCHAR(32)  NOT NULL DEFAULT 'project', -- project | global
    "TenantId"           VARCHAR(128) NOT NULL DEFAULT 'default', -- denormalizado de projects.tenant_id
    "AllowedProjectIds"  JSONB        NULL,                     -- whitelist quando Visibility=global
    "CreatedAt"          TIMESTAMPTZ  NOT NULL,
    "UpdatedAt"          TIMESTAMPTZ  NOT NULL,
    CONSTRAINT "PK_agent_definitions" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_agent_definitions_Visibility" CHECK ("Visibility" IN ('project', 'global'))
);

-- Coluna AllowedProjectIds idempotente. Backfill = NULL (sem whitelist).
ALTER TABLE aihub.agent_definitions
    ADD COLUMN IF NOT EXISTS "AllowedProjectIds" JSONB NULL;

-- ALTER idempotente pra DBs existentes (agent sharing — Visibility/TenantId).
ALTER TABLE aihub.agent_definitions
    ADD COLUMN IF NOT EXISTS "Visibility" VARCHAR(32) NOT NULL DEFAULT 'project';
ALTER TABLE aihub.agent_definitions
    ADD COLUMN IF NOT EXISTS "TenantId" VARCHAR(128) NOT NULL DEFAULT 'default';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'CK_agent_definitions_Visibility'
    ) THEN
        ALTER TABLE aihub.agent_definitions
            ADD CONSTRAINT "CK_agent_definitions_Visibility"
            CHECK ("Visibility" IN ('project', 'global')) NOT VALID;
        ALTER TABLE aihub.agent_definitions
            VALIDATE CONSTRAINT "CK_agent_definitions_Visibility";
    END IF;
END $$;

-- Backfill TenantId via JOIN com projects (idempotente).
UPDATE aihub.agent_definitions ad
SET "TenantId" = p.tenant_id
FROM aihub.projects p
WHERE ad."ProjectId" = p.id
  AND ad."TenantId" = 'default'
  AND p.tenant_id <> 'default';

-- Index parcial: listagens cross-project só atravessam agents globais.
CREATE INDEX IF NOT EXISTS "IX_agent_definitions_TenantId_Visibility"
    ON aihub.agent_definitions ("TenantId")
    WHERE "Visibility" = 'global';

CREATE TABLE IF NOT EXISTS aihub.workflow_definitions (
    "Id"         VARCHAR(256) NOT NULL,
    "Name"       VARCHAR(512) NOT NULL,
    "Data"       TEXT         NOT NULL,                 -- JSON serializado do WorkflowDef
    "ProjectId"  VARCHAR(128) NOT NULL DEFAULT 'default',
    "Visibility" VARCHAR(32)  NOT NULL DEFAULT 'project', -- project | global
    "TenantId"   VARCHAR(128) NOT NULL DEFAULT 'default', -- denormalizado de projects.tenant_id (tenant boundary em listagens cross-project)
    "CreatedAt"  TIMESTAMPTZ  NOT NULL,
    "UpdatedAt"  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT "PK_workflow_definitions" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_workflow_definitions_Visibility" CHECK ("Visibility" IN ('project', 'global'))
);

-- ALTER idempotente pra DBs existentes (DatabaseBootstrapService re-roda este script no startup).
-- ADD COLUMN com DEFAULT é metadata-only no PG 11+ (sem rewrite).
ALTER TABLE aihub.workflow_definitions
    ADD COLUMN IF NOT EXISTS "TenantId" VARCHAR(128) NOT NULL DEFAULT 'default';

-- CHECK constraint adicionado em duas etapas pra ser safe em DBs com dados antigos
-- (NOT VALID + VALIDATE) — porém como a constraint só existe se a tabela for nova,
-- aplicamos via DO block que ignora se já existe.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'CK_workflow_definitions_Visibility'
    ) THEN
        ALTER TABLE aihub.workflow_definitions
            ADD CONSTRAINT "CK_workflow_definitions_Visibility"
            CHECK ("Visibility" IN ('project', 'global')) NOT VALID;
        ALTER TABLE aihub.workflow_definitions
            VALIDATE CONSTRAINT "CK_workflow_definitions_Visibility";
    END IF;
END $$;

-- Backfill TenantId via JOIN com projects (idempotente — só atualiza rows com 'default' inconsistente).
UPDATE aihub.workflow_definitions wd
SET "TenantId" = p.tenant_id
FROM aihub.projects p
WHERE wd."ProjectId" = p.id
  AND wd."TenantId" = 'default'
  AND p.tenant_id <> 'default';

-- Index parcial: listagens cross-project só atravessam workflows globais; índice cobre o filtro hot path.
CREATE INDEX IF NOT EXISTS "IX_workflow_definitions_TenantId_Visibility"
    ON aihub.workflow_definitions ("TenantId")
    WHERE "Visibility" = 'global';

-- =============================================================================
-- 3. VERSIONAMENTO DE AGENTES E WORKFLOWS (snapshots imutáveis)
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.agent_versions (
    "AgentVersionId"    VARCHAR(64)   NOT NULL,
    "AgentDefinitionId" VARCHAR(256)  NOT NULL,
    "Revision"          INTEGER       NOT NULL,
    "CreatedAt"         TIMESTAMPTZ   NOT NULL,
    "CreatedBy"         VARCHAR(256)  NULL,
    "ChangeReason"      VARCHAR(1024) NULL,
    "Status"            VARCHAR(32)   NOT NULL,         -- Draft | Published | Deprecated
    "ContentHash"       VARCHAR(128)  NOT NULL,
    "Snapshot"          JSONB         NOT NULL,         -- snapshot completo do agente no momento do publish
    "BreakingChange"    BOOLEAN       NULL,             -- true=breaking; false=patch; null=legacy/unknown
    "SchemaVersion"     INTEGER       NOT NULL DEFAULT 1, -- 1=lossy legacy; 2=lossless (Tools cheias + Description/Metadata/FallbackProvider)
    CONSTRAINT "PK_agent_versions" PRIMARY KEY ("AgentVersionId")
);

-- ALTER idempotente pra DBs existentes.
ALTER TABLE aihub.agent_versions
    ADD COLUMN IF NOT EXISTS "BreakingChange" BOOLEAN NULL;
ALTER TABLE aihub.agent_versions
    ADD COLUMN IF NOT EXISTS "SchemaVersion" INTEGER NOT NULL DEFAULT 1;

CREATE UNIQUE INDEX IF NOT EXISTS "IX_agent_versions_AgentDefinitionId_Revision"
    ON aihub.agent_versions ("AgentDefinitionId", "Revision");

CREATE INDEX IF NOT EXISTS "IX_agent_versions_AgentDefinitionId"
    ON aihub.agent_versions ("AgentDefinitionId");

CREATE INDEX IF NOT EXISTS "IX_agent_versions_ContentHash"
    ON aihub.agent_versions ("ContentHash");

-- Index parcial cobre o predicate "alguma version BreakingChange=true entre rev_pinned e rev_current"
-- usado pela patch propagation. Como breaking é raro, parcial mantém o índice pequeno.
CREATE INDEX IF NOT EXISTS "IX_agent_versions_AgentDefId_Breaking"
    ON aihub.agent_versions ("AgentDefinitionId", "Revision")
    WHERE "BreakingChange" = TRUE;

CREATE TABLE IF NOT EXISTS aihub.workflow_versions (
    "WorkflowVersionId"    VARCHAR(64)   NOT NULL,
    "WorkflowDefinitionId" VARCHAR(256)  NOT NULL,
    "Revision"             INTEGER       NOT NULL,
    "CreatedAt"            TIMESTAMPTZ   NOT NULL,
    "CreatedBy"            VARCHAR(256)  NULL,
    "ChangeReason"         VARCHAR(1024) NULL,
    "Status"               VARCHAR(32)   NOT NULL,
    "ContentHash"          VARCHAR(128)  NOT NULL,
    "Snapshot"             JSONB         NOT NULL,
    CONSTRAINT "PK_workflow_versions" PRIMARY KEY ("WorkflowVersionId")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_workflow_versions_WorkflowDefinitionId_Revision"
    ON aihub.workflow_versions ("WorkflowDefinitionId", "Revision");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_workflow_versions_WorkflowDefinitionId_ContentHash"
    ON aihub.workflow_versions ("WorkflowDefinitionId", "ContentHash");

CREATE INDEX IF NOT EXISTS "IX_workflow_versions_WorkflowDefinitionId"
    ON aihub.workflow_versions ("WorkflowDefinitionId");

-- =============================================================================
-- 4. VERSIONAMENTO DE PROMPTS
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.agent_prompt_versions (
    "RowId"     INTEGER      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "AgentId"   VARCHAR(256) NOT NULL,
    "VersionId" VARCHAR(128) NOT NULL,
    "Content"   TEXT         NOT NULL,
    "IsActive"  BOOLEAN      NOT NULL,
    "CreatedAt" TIMESTAMPTZ  NOT NULL,
    CONSTRAINT "PK_agent_prompt_versions" PRIMARY KEY ("RowId")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_agent_prompt_versions_AgentId_VersionId"
    ON aihub.agent_prompt_versions ("AgentId", "VersionId");

CREATE INDEX IF NOT EXISTS "IX_agent_prompt_versions_AgentId"
    ON aihub.agent_prompt_versions ("AgentId");

-- =============================================================================
-- 5. SKILLS (reutilizáveis entre agentes)
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.skills (
    "Id"          VARCHAR(256) NOT NULL,
    "Name"        VARCHAR(256) NOT NULL,
    "Data"        JSONB        NOT NULL,
    "ContentHash" VARCHAR(128) NOT NULL,
    "CreatedAt"   TIMESTAMPTZ  NOT NULL,
    "UpdatedAt"   TIMESTAMPTZ  NOT NULL,
    "ProjectId"   VARCHAR(128) NOT NULL DEFAULT 'default',
    CONSTRAINT "PK_skills" PRIMARY KEY ("Id")
);

-- Garante coluna em bancos existentes (idempotente)
ALTER TABLE aihub.skills
    ADD COLUMN IF NOT EXISTS "ProjectId" VARCHAR(128) NOT NULL DEFAULT 'default';

CREATE INDEX IF NOT EXISTS "IX_skills_ProjectId" ON aihub.skills ("ProjectId");

CREATE TABLE IF NOT EXISTS aihub.skill_versions (
    "SkillVersionId" VARCHAR(64)   NOT NULL,
    "SkillId"        VARCHAR(256)  NOT NULL,
    "Revision"       INTEGER       NOT NULL,
    "CreatedAt"      TIMESTAMPTZ   NOT NULL,
    "CreatedBy"      VARCHAR(256)  NULL,
    "ChangeReason"   VARCHAR(1024) NULL,
    "ContentHash"    VARCHAR(128)  NOT NULL,
    "Snapshot"       JSONB         NOT NULL,
    CONSTRAINT "PK_skill_versions" PRIMARY KEY ("SkillVersionId")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_skill_versions_SkillId_Revision"
    ON aihub.skill_versions ("SkillId", "Revision");

CREATE INDEX IF NOT EXISTS "IX_skill_versions_SkillId"
    ON aihub.skill_versions ("SkillId");

CREATE INDEX IF NOT EXISTS "IX_skill_versions_ContentHash"
    ON aihub.skill_versions ("ContentHash");

-- =============================================================================
-- 5.1 MCP SERVERS (Model Context Protocol — registry centralizado)
-- =============================================================================
-- Agents referenciam servidores MCP pelo Id deste registro. A coluna Data
-- JSONB guarda o McpServer completo (ServerLabel, ServerUrl, AllowedTools,
-- Headers, RequireApproval, Description). Project-scoped.

CREATE TABLE IF NOT EXISTS aihub.mcp_servers (
    "Id"         VARCHAR(128) NOT NULL,
    "Name"       VARCHAR(256) NOT NULL,
    "Data"       JSONB        NOT NULL,
    "ProjectId"  VARCHAR(128) NOT NULL DEFAULT 'default',
    "CreatedAt"  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_mcp_servers" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_mcp_servers_ProjectId_Name"
    ON aihub.mcp_servers ("ProjectId", "Name");

-- =============================================================================
-- 6. EXECUÇÕES DE WORKFLOW
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.workflow_executions (
    "ExecutionId" VARCHAR(128) NOT NULL,
    "WorkflowId"  VARCHAR(256) NOT NULL,
    "ProjectId"   VARCHAR(128) NOT NULL DEFAULT 'default',
    "Status"      VARCHAR(32)  NOT NULL,                -- Pending | Running | Completed | Failed | Cancelled
    "Data"        TEXT         NOT NULL,
    "StartedAt"   TIMESTAMPTZ  NOT NULL,
    "CompletedAt" TIMESTAMPTZ  NULL,
    CONSTRAINT "PK_workflow_executions" PRIMARY KEY ("ExecutionId")
);

CREATE INDEX IF NOT EXISTS "IX_workflow_executions_WorkflowId"
    ON aihub.workflow_executions ("WorkflowId");

CREATE INDEX IF NOT EXISTS "IX_workflow_executions_Status"
    ON aihub.workflow_executions ("Status");

CREATE INDEX IF NOT EXISTS "IX_workflow_executions_StartedAt"
    ON aihub.workflow_executions ("StartedAt");

CREATE INDEX IF NOT EXISTS "IX_workflow_executions_WorkflowId_Status_StartedAt"
    ON aihub.workflow_executions ("WorkflowId", "Status", "StartedAt" DESC);

-- =============================================================================
-- 7. NÓS DE EXECUÇÃO (Graph mode)
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.node_executions (
    "RowId"       INTEGER      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ExecutionId" VARCHAR(128) NOT NULL,
    "NodeId"      VARCHAR(256) NOT NULL,
    "Data"        TEXT         NOT NULL,
    "ProjectId"   VARCHAR(128) NULL,  -- F4 — boundary de isolamento (ADR 003)
    CONSTRAINT "PK_node_executions" PRIMARY KEY ("RowId")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_node_executions_ExecutionId_NodeId"
    ON aihub.node_executions ("ExecutionId", "NodeId");

CREATE INDEX IF NOT EXISTS "IX_node_executions_ExecutionId"
    ON aihub.node_executions ("ExecutionId");

CREATE INDEX IF NOT EXISTS ix_node_executions_project_exec
    ON aihub.node_executions ("ProjectId", "ExecutionId");

-- =============================================================================
-- 8. CHECKPOINTS DE WORKFLOW
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.workflow_checkpoints (
    "ExecutionId" VARCHAR(128) NOT NULL,
    "Data"        BYTEA        NOT NULL,                -- estado serializado binário
    "UpdatedAt"   TIMESTAMPTZ  NOT NULL,
    CONSTRAINT "PK_workflow_checkpoints" PRIMARY KEY ("ExecutionId")
);

-- =============================================================================
-- 9. AUDITORIA DE EVENTOS DE WORKFLOW
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.workflow_event_audit (
    "Id"          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ExecutionId" VARCHAR(128) NOT NULL,
    "EventType"   VARCHAR(64)  NOT NULL,
    "Payload"     TEXT         NOT NULL,
    "Timestamp"   TIMESTAMPTZ  NOT NULL,
    CONSTRAINT "PK_workflow_event_audit" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_workflow_event_audit_ExecutionId"
    ON aihub.workflow_event_audit ("ExecutionId");

CREATE INDEX IF NOT EXISTS "IX_workflow_event_audit_ExecutionId_Id"
    ON aihub.workflow_event_audit ("ExecutionId", "Id");

CREATE INDEX IF NOT EXISTS "IX_workflow_event_audit_Timestamp"
    ON aihub.workflow_event_audit ("Timestamp");

-- Trilha de auditoria de mudanças CRUD em recursos administrativos
-- (Project, Agent, Workflow, Skill, ModelPricing). Escrita pelos controllers
-- Admin via IAdminAuditLogger. Retention: AuditRetentionDays (default 90).
CREATE TABLE IF NOT EXISTS aihub.admin_audit_log (
    "Id"            BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "TenantId"      VARCHAR(128) NULL,
    "ProjectId"     VARCHAR(128) NULL,
    "ActorUserId"   VARCHAR(128) NOT NULL,
    "ActorUserType" VARCHAR(32)  NULL,
    "Action"        VARCHAR(64)  NOT NULL,
    "ResourceType"  VARCHAR(64)  NOT NULL,
    "ResourceId"    VARCHAR(128) NOT NULL,
    "PayloadBefore" JSONB        NULL,
    "PayloadAfter"  JSONB        NULL,
    "Timestamp"     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_admin_audit_log" PRIMARY KEY ("Id")
);

-- ALTER idempotente: action keys cresceram com novas constants
-- (workflow.agent_version_auto_pinned tem 35 chars; legacy schema usava VARCHAR(32)).
ALTER TABLE aihub.admin_audit_log
    ALTER COLUMN "Action" TYPE VARCHAR(64);

CREATE INDEX IF NOT EXISTS "IX_admin_audit_log_TenantId_Timestamp"
    ON aihub.admin_audit_log ("TenantId", "Timestamp" DESC);

CREATE INDEX IF NOT EXISTS "IX_admin_audit_log_ResourceType_ResourceId"
    ON aihub.admin_audit_log ("ResourceType", "ResourceId");

CREATE INDEX IF NOT EXISTS "IX_admin_audit_log_ActorUserId_Timestamp"
    ON aihub.admin_audit_log ("ActorUserId", "Timestamp" DESC);

-- =============================================================================
-- 10. CONVERSAS E MENSAGENS (Chat)
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.conversations (
    "ConversationId"    VARCHAR(64)  NOT NULL,
    "UserId"            VARCHAR(256) NOT NULL,
    "UserType"          TEXT         NULL,
    "WorkflowId"        VARCHAR(256) NOT NULL,
    "Title"             VARCHAR(512) NULL,
    "ActiveExecutionId" VARCHAR(64)  NULL,
    "LastActiveAgentId" VARCHAR(256) NULL,
    "ContextClearedAt"  TIMESTAMPTZ  NULL,
    "ProjectId"         VARCHAR(128) NOT NULL DEFAULT 'default',
    "CreatedAt"         TIMESTAMPTZ  NOT NULL,
    "LastMessageAt"     TIMESTAMPTZ  NOT NULL,
    "Metadata"          JSONB        NOT NULL DEFAULT '{}',
    CONSTRAINT "PK_conversations" PRIMARY KEY ("ConversationId")
);

CREATE INDEX IF NOT EXISTS "IX_conversations_UserId"
    ON aihub.conversations ("UserId");

CREATE INDEX IF NOT EXISTS "IX_conversations_LastMessageAt"
    ON aihub.conversations ("LastMessageAt");

CREATE TABLE IF NOT EXISTS aihub.chat_messages (
    "MessageId"        VARCHAR(64)  NOT NULL,
    "ConversationId"   VARCHAR(64)  NOT NULL,
    "Role"             VARCHAR(32)  NOT NULL,           -- user | assistant | system | tool (5 canônicos AG-UI)
    "Content"          TEXT         NOT NULL,
    "StructuredOutput" JSONB        NULL,
    "CreatedAt"        TIMESTAMPTZ  NOT NULL,
    "TokenCount"       INTEGER      NOT NULL,
    "ExecutionId"      VARCHAR(64)  NULL,
    "Actor"            VARCHAR(32)  NOT NULL DEFAULT 'human',  -- human | robot — proveniência aditiva à Role (ver ADR 0014)
    CONSTRAINT "PK_chat_messages" PRIMARY KEY ("MessageId")
);

-- ALTER aditivo idempotente: aplica a coluna Actor em bancos legados sem CREATE TABLE novo.
ALTER TABLE aihub.chat_messages
    ADD COLUMN IF NOT EXISTS "Actor" VARCHAR(32) NOT NULL DEFAULT 'human';

CREATE INDEX IF NOT EXISTS "IX_chat_messages_ConversationId"
    ON aihub.chat_messages ("ConversationId");

CREATE INDEX IF NOT EXISTS "IX_chat_messages_ConversationId_CreatedAt"
    ON aihub.chat_messages ("ConversationId", "CreatedAt");

-- =============================================================================
-- 11. INTERAÇÕES HUMANAS (HITL — Human-in-the-Loop)
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.human_interactions (
    "InteractionId" VARCHAR(128) NOT NULL,
    "ExecutionId"   VARCHAR(128) NOT NULL,
    "WorkflowId"    VARCHAR(256) NOT NULL,
    "Prompt"        TEXT         NOT NULL,
    "Context"       TEXT         NULL,
    "InteractionType" VARCHAR(32) NOT NULL DEFAULT 'Approval', -- Approval | Input | Choice
    "Options"       TEXT         NULL,                  -- JSON array de opções (ex: ["Confirmar","Cancelar"])
    "Status"        VARCHAR(32)  NOT NULL,              -- Pending | Approved | Rejected | Expired
    "Resolution"    TEXT         NULL,
    "CreatedAt"     TIMESTAMPTZ  NOT NULL,
    "ResolvedAt"    TIMESTAMPTZ  NULL,
    "ResolvedBy"    VARCHAR(128) NULL,                  -- UserId de quem resolveu; 'system:timeout' para expiração automática
    CONSTRAINT "PK_human_interactions" PRIMARY KEY ("InteractionId")
);

CREATE INDEX IF NOT EXISTS "IX_human_interactions_ExecutionId"
    ON aihub.human_interactions ("ExecutionId");

CREATE INDEX IF NOT EXISTS "IX_human_interactions_Status"
    ON aihub.human_interactions ("Status");

-- Auditoria: "minhas resoluções HITL" — queries por quem resolveu em dado período.
CREATE INDEX IF NOT EXISTS "IX_human_interactions_ResolvedBy_ResolvedAt"
    ON aihub.human_interactions ("ResolvedBy", "ResolvedAt" DESC)
    WHERE "ResolvedBy" IS NOT NULL;

-- =============================================================================
-- 12. SESSÕES DE AGENTE
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.agent_sessions (
    "SessionId"       VARCHAR(128) NOT NULL,
    "AgentId"         VARCHAR(256) NOT NULL,
    "SerializedState" TEXT         NOT NULL,
    "TurnCount"       INTEGER      NOT NULL DEFAULT 0,
    "CreatedAt"       TIMESTAMPTZ  NOT NULL,
    "LastAccessedAt"  TIMESTAMPTZ  NOT NULL,
    "ExpiresAt"       TIMESTAMPTZ  NOT NULL,
    CONSTRAINT "PK_agent_sessions" PRIMARY KEY ("SessionId")
);

CREATE INDEX IF NOT EXISTS "IX_agent_sessions_AgentId"
    ON aihub.agent_sessions ("AgentId");

CREATE INDEX IF NOT EXISTS "IX_agent_sessions_ExpiresAt"
    ON aihub.agent_sessions ("ExpiresAt");

-- =============================================================================
-- 13. JOBS DE BACKGROUND (respostas assíncronas de agentes)
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.background_response_jobs (
    "JobId"           VARCHAR(64)  NOT NULL,
    "AgentId"         VARCHAR(256) NOT NULL,
    "AgentVersionId"  VARCHAR(64)  NULL,
    "SessionId"       VARCHAR(128) NULL,
    "Input"           TEXT         NOT NULL,
    "Status"          VARCHAR(32)  NOT NULL,            -- Queued | Running | Completed | Failed
    "Output"          TEXT         NULL,
    "LastError"       TEXT         NULL,
    "Attempt"         INTEGER      NOT NULL DEFAULT 0,
    "CallbackTarget"  JSONB        NULL,
    "IdempotencyKey"  VARCHAR(128) NULL,
    "CreatedAt"       TIMESTAMPTZ  NOT NULL,
    "StartedAt"       TIMESTAMPTZ  NULL,
    "CompletedAt"     TIMESTAMPTZ  NULL,
    CONSTRAINT "PK_background_response_jobs" PRIMARY KEY ("JobId")
);

CREATE INDEX IF NOT EXISTS "IX_background_response_jobs_Status_CreatedAt"
    ON aihub.background_response_jobs ("Status", "CreatedAt");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_background_response_jobs_IdempotencyKey"
    ON aihub.background_response_jobs ("IdempotencyKey")
    WHERE "IdempotencyKey" IS NOT NULL;

-- =============================================================================
-- 14. OBSERVABILIDADE — USO DE TOKENS LLM
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.llm_token_usage (
    "Id"              BIGINT           NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "AgentId"         VARCHAR(256)     NOT NULL,
    "ModelId"         VARCHAR(256)     NOT NULL,
    "ExecutionId"     VARCHAR(128)     NULL,
    "WorkflowId"      VARCHAR(256)     NULL,
    "InputTokens"     INTEGER          NOT NULL,
    "OutputTokens"    INTEGER          NOT NULL,
    "TotalTokens"     INTEGER          NOT NULL,
    "CachedTokens"    INTEGER          NOT NULL DEFAULT 0,  -- F1 — OpenAI prompt cache hits
    "DurationMs"      DOUBLE PRECISION NOT NULL,
    "PromptVersionId" VARCHAR(128)     NULL,
    "AgentVersionId"  VARCHAR(64)      NULL,  -- rastreia snapshot do agente na execução
    "OutputContent"   TEXT             NULL,
    "RetryCount"      INTEGER          NOT NULL DEFAULT 0,
    "ProjectId"            VARCHAR(128) NULL,  -- F4 — boundary de isolamento (ADR 003) / caller (consumer)
    "OriginAgentProjectId" VARCHAR(128) NULL,  -- owner do agent quando cross-project (NULL se local)
    "CreatedAt"            TIMESTAMPTZ  NOT NULL,
    CONSTRAINT "PK_llm_token_usage" PRIMARY KEY ("Id")
);

-- ALTER idempotente pra DBs existentes (agent sharing — OriginAgentProjectId).
ALTER TABLE aihub.llm_token_usage
    ADD COLUMN IF NOT EXISTS "OriginAgentProjectId" VARCHAR(128) NULL;

CREATE INDEX IF NOT EXISTS "IX_llm_token_usage_AgentId"
    ON aihub.llm_token_usage ("AgentId");

CREATE INDEX IF NOT EXISTS "IX_llm_token_usage_ExecutionId"
    ON aihub.llm_token_usage ("ExecutionId");

CREATE INDEX IF NOT EXISTS "IX_llm_token_usage_CreatedAt"
    ON aihub.llm_token_usage ("CreatedAt");

CREATE INDEX IF NOT EXISTS ix_llm_token_usage_project_created
    ON aihub.llm_token_usage ("ProjectId", "CreatedAt" DESC);

-- Analytics dual: "qual projeto pagou X tokens com agent global de Y".
CREATE INDEX IF NOT EXISTS "IX_llm_token_usage_caller_origin"
    ON aihub.llm_token_usage ("ProjectId", "OriginAgentProjectId", "CreatedAt" DESC);

-- =============================================================================
-- 15. OBSERVABILIDADE — INVOCAÇÕES DE TOOLS
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.tool_invocations (
    "Id"           BIGINT           NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ExecutionId"  VARCHAR(128)     NOT NULL,
    "AgentId"      VARCHAR(256)     NOT NULL,
    "ToolName"     VARCHAR(256)     NOT NULL,
    "Arguments"    JSONB            NULL,
    "Result"       TEXT             NULL,
    "DurationMs"   DOUBLE PRECISION NOT NULL,
    "Success"      BOOLEAN          NOT NULL,
    "ErrorMessage" TEXT             NULL,
    "CreatedAt"    TIMESTAMPTZ      NOT NULL,
    CONSTRAINT "PK_tool_invocations" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_tool_invocations_ExecutionId"
    ON aihub.tool_invocations ("ExecutionId");

CREATE INDEX IF NOT EXISTS "IX_tool_invocations_AgentId"
    ON aihub.tool_invocations ("AgentId");

CREATE INDEX IF NOT EXISTS "IX_tool_invocations_ToolName"
    ON aihub.tool_invocations ("ToolName");

-- =============================================================================
-- 16. PRECIFICAÇÃO DE MODELOS LLM
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.model_pricing (
    "Id"                  INTEGER        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ModelId"             VARCHAR(256)   NOT NULL,
    "Provider"            VARCHAR(64)    NOT NULL,
    "PricePerInputToken"  NUMERIC(20,10) NOT NULL,
    "PricePerOutputToken" NUMERIC(20,10) NOT NULL,
    "Currency"            VARCHAR(3)     NOT NULL DEFAULT 'USD',
    "EffectiveFrom"       TIMESTAMPTZ    NOT NULL,
    "EffectiveTo"         TIMESTAMPTZ    NULL,
    "CreatedAt"           TIMESTAMPTZ    NOT NULL,
    CONSTRAINT "PK_model_pricing" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_model_pricing_ModelId"
    ON aihub.model_pricing ("ModelId");

-- =============================================================================
-- 16b. DOCUMENT INTELLIGENCE — Pricing por página
-- Azure Document Intelligence cobra por página processada (unidade diferente
-- de LLM que é por token). Tabela separada evita misturar semântica.
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.document_intelligence_pricing (
    "Id"            INTEGER        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ModelId"       VARCHAR(128)   NOT NULL,   -- prebuilt-layout | prebuilt-read | prebuilt-invoice | ...
    "Provider"      VARCHAR(64)    NOT NULL,   -- AZUREAI (único hoje)
    "PricePerPage"  NUMERIC(20,10) NOT NULL,   -- USD por 1 página
    "Currency"      VARCHAR(3)     NOT NULL DEFAULT 'USD',
    "EffectiveFrom" TIMESTAMPTZ    NOT NULL,
    "EffectiveTo"   TIMESTAMPTZ    NULL,
    "CreatedAt"     TIMESTAMPTZ    NOT NULL,
    CONSTRAINT "PK_document_intelligence_pricing" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_document_intelligence_pricing_ModelId"
    ON aihub.document_intelligence_pricing ("ModelId");

-- =============================================================================
-- 17. ATIVOS FINANCEIROS
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.ativos (
    "Ticker"    VARCHAR(20)  NOT NULL,
    "Nome"      VARCHAR(255) NOT NULL,
    "Setor"     VARCHAR(100) NULL,
    "Descricao" TEXT         NULL,
    "CreatedAt" TIMESTAMPTZ  NOT NULL,
    "UpdatedAt" TIMESTAMPTZ  NOT NULL,
    CONSTRAINT "PK_ativos" PRIMARY KEY ("Ticker")
);

CREATE INDEX IF NOT EXISTS "IX_ativos_Setor"
    ON aihub.ativos ("Setor");

-- =============================================================================
-- 18. CATÁLOGO DE MODELOS LLM
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.model_catalog (
    id             VARCHAR(128)  NOT NULL,
    provider       VARCHAR(64)   NOT NULL,   -- OPENAI | AZUREOPENAI | AZUREFOUNDRY
    display_name   VARCHAR(256)  NOT NULL,
    description    TEXT          NULL,
    context_window INTEGER       NULL,
    capabilities   JSONB         NOT NULL DEFAULT '[]', -- ["chat","vision","function_calling"]
    is_active      BOOLEAN       NOT NULL DEFAULT true,
    created_at     TIMESTAMPTZ   NOT NULL,
    updated_at     TIMESTAMPTZ   NOT NULL,
    CONSTRAINT pk_model_catalog PRIMARY KEY (id, provider)
);

CREATE INDEX IF NOT EXISTS ix_model_catalog_provider
    ON aihub.model_catalog (provider);

CREATE INDEX IF NOT EXISTS ix_model_catalog_is_active
    ON aihub.model_catalog (is_active);

-- =============================================================================
-- 19. DOCUMENT INTELLIGENCE — EXTRAÇÃO DE DOCUMENTOS
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.document_extraction_jobs (
    id                  UUID PRIMARY KEY,
    conversation_id     TEXT NOT NULL,
    user_id             TEXT NOT NULL,
    source_type         TEXT NOT NULL,
    source_ref          TEXT,
    content_sha256      TEXT NOT NULL,
    model               TEXT NOT NULL,
    features_hash       TEXT,
    status              TEXT NOT NULL DEFAULT 'created',
    operation_id        TEXT,
    result_ref          TEXT,
    page_count          INT,
    cost_usd            NUMERIC(12,6),
    error_code          TEXT,
    error_message       TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at          TIMESTAMPTZ,
    finished_at         TIMESTAMPTZ,
    duration_ms         INT,

    CONSTRAINT chk_dej_status CHECK (
        status IN ('created', 'running', 'succeeded', 'failed', 'cached')
    ),
    CONSTRAINT chk_dej_error_code CHECK (
        error_code IS NULL OR error_code IN (
            'PAGE_LIMIT_EXCEEDED',
            'UNREADABLE_PDF',
            'SOURCE_UNAVAILABLE',
            'AZURE_DI_FAILURE',
            'TIMEOUT',
            'GATE_TIMEOUT',
            'CANCELLED'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_dej_hash_model
    ON aihub.document_extraction_jobs(content_sha256, model);

CREATE INDEX IF NOT EXISTS idx_dej_conversation
    ON aihub.document_extraction_jobs(conversation_id);

CREATE INDEX IF NOT EXISTS idx_dej_status_created
    ON aihub.document_extraction_jobs(status, created_at);

CREATE TABLE IF NOT EXISTS aihub.document_extraction_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id       UUID NOT NULL REFERENCES aihub.document_extraction_jobs(id),
    event_type   TEXT NOT NULL,
    detail       JSONB,
    occurred_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_dee_job
    ON aihub.document_extraction_events(job_id, occurred_at);

CREATE TABLE IF NOT EXISTS aihub.document_extraction_cache (
    content_sha256      TEXT NOT NULL,
    model               TEXT NOT NULL,
    features_hash       TEXT NOT NULL,
    result_ref          TEXT NOT NULL,
    page_count          INT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at          TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (content_sha256, model, features_hash)
);

-- =============================================================================
-- 20. PERSONA PROMPT TEMPLATES — texto que compõe o bloco de persona no
--     system message do LLM. Placeholders {{segment}}, {{risk_profile}}, etc
--     são substituídos em runtime pelo PersonaPromptComposer.
--
--     Scope: 'global' (default aplicado a todos os agentes) ou 'agent:{agentId}'
--     (override específico). Lookup do runtime: agent-specific → global → null.
--
--     Update in-place (sem versionamento de linha): UPDATE substitui o template.
--     Auditoria de mudanças via admin_audit_log (resource_type='persona_prompt_template').
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.persona_prompt_templates (
    "Id"              SERIAL PRIMARY KEY,
    "Scope"           VARCHAR(128) NOT NULL,
    "Name"            VARCHAR(128) NOT NULL,
    "Template"        TEXT NOT NULL,
    "CreatedAt"       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UpdatedAt"       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UpdatedBy"       VARCHAR(128) NULL,
    "ActiveVersionId" UUID NULL,  -- F5 — aponta pra version ativa em persona_prompt_template_versions
    CONSTRAINT template_length CHECK (LENGTH("Template") <= 50000)  -- F3
);

-- F5 — histórico append-only de versions.
CREATE TABLE IF NOT EXISTS aihub.persona_prompt_template_versions (
    "Id"             SERIAL PRIMARY KEY,
    "TemplateId"     INT NOT NULL REFERENCES aihub.persona_prompt_templates("Id") ON DELETE CASCADE,
    "VersionId"      UUID NOT NULL DEFAULT gen_random_uuid(),
    "Template"       TEXT NOT NULL,
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "CreatedBy"      VARCHAR(128) NULL,
    "ChangeReason"   VARCHAR(512) NULL,
    CONSTRAINT template_length_version CHECK (LENGTH("Template") <= 50000)
);

CREATE INDEX IF NOT EXISTS ix_ptv_template_created
    ON aihub.persona_prompt_template_versions("TemplateId", "CreatedAt" DESC);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ptv_version_id
    ON aihub.persona_prompt_template_versions("VersionId");

-- UNIQUE(Scope): 1 template ativo por scope. Conflitos de escrita concorrente
-- resolvidos no controller via upsert.
CREATE UNIQUE INDEX IF NOT EXISTS "UX_persona_prompt_templates_Scope"
    ON aihub.persona_prompt_templates ("Scope");

-- =============================================================================
-- F6 — A/B testing de templates (persona_prompt_experiments)
-- Ver docs/adr/005-persona-ab-testing.md e db/migration_persona_experiments.sql
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.persona_prompt_experiments (
    "Id"                 SERIAL PRIMARY KEY,
    "ProjectId"          VARCHAR(128) NOT NULL,
    "Scope"              VARCHAR(128) NOT NULL,
    "Name"               VARCHAR(128) NOT NULL,
    "VariantAVersionId"  UUID NOT NULL,
    "VariantBVersionId"  UUID NOT NULL,
    "TrafficSplitB"      INT NOT NULL CHECK ("TrafficSplitB" BETWEEN 0 AND 100),
    "Metric"             VARCHAR(64) NOT NULL,
    "StartedAt"          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "EndedAt"            TIMESTAMPTZ NULL,
    "CreatedBy"          VARCHAR(128) NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_persona_experiments_active
    ON aihub.persona_prompt_experiments("ProjectId", "Scope")
    WHERE "EndedAt" IS NULL;

CREATE INDEX IF NOT EXISTS ix_persona_experiments_project
    ON aihub.persona_prompt_experiments("ProjectId", "StartedAt" DESC);

-- F6 — outcome binding: llm_token_usage guarda experiment + variant.
ALTER TABLE aihub.llm_token_usage
    ADD COLUMN IF NOT EXISTS "ExperimentId" INT NULL,
    ADD COLUMN IF NOT EXISTS "ExperimentVariant" CHAR(1) NULL
        CHECK ("ExperimentVariant" IN ('A', 'B'));

CREATE INDEX IF NOT EXISTS ix_llm_token_usage_experiment
    ON aihub.llm_token_usage("ExperimentId")
    WHERE "ExperimentId" IS NOT NULL;

-- =============================================================================
-- FIM DO SCHEMA
-- =============================================================================

-- =============================================================================
-- Deprecação F9: coluna UpdatedBy em persona_prompt_templates
--
-- Actor canônico vive em admin_audit_log (via IAdminAuditLogger). Coluna
-- não é mais lida nem escrita pelo app (ver ADR 008). DROP idempotente:
-- em ambiente novo o CREATE TABLE já não cria; em ambiente com coluna
-- legada, DROP IF EXISTS remove.
-- =============================================================================
ALTER TABLE aihub.persona_prompt_templates DROP COLUMN IF EXISTS "UpdatedBy";

-- =============================================================================
-- Blocklist Guardrail v1 — catálogo curado de patterns
--
-- Catálogo é gerenciado pelo DBA via edição deste seeds.sql + apply.sh.
-- Override por projeto vive em ProjectSettings.Blocklist (JSONB), não aqui.
--
-- Trigger pg_notify('blocklist_changed', '') propaga mudanças do catálogo
-- para todos os pods (cache hybrid L1+L2 invalida via PgNotifyDispatcher).
-- TTL do cache (60s) cobre falha de NOTIFY como fallback.
-- =============================================================================
CREATE TABLE IF NOT EXISTS aihub.blocklist_pattern_groups (
    "Id"          VARCHAR(64)  PRIMARY KEY,
    "Name"        VARCHAR(128) NOT NULL,
    "Description" TEXT NULL,
    "Version"     INT          NOT NULL DEFAULT 1,
    "CreatedAt"   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS aihub.blocklist_patterns (
    "Id"            VARCHAR(128) PRIMARY KEY,
    "GroupId"       VARCHAR(64)  NOT NULL REFERENCES aihub.blocklist_pattern_groups("Id") ON DELETE CASCADE,
    "Type"          VARCHAR(16)  NOT NULL CHECK ("Type" IN ('literal', 'regex', 'builtin')),
    "Pattern"       TEXT         NOT NULL,
    "ValidatorFn"   VARCHAR(32)  NULL CHECK ("ValidatorFn" IS NULL OR "ValidatorFn" IN ('mod11', 'luhn')),
    "WholeWord"     BOOLEAN      NOT NULL DEFAULT TRUE,
    "CaseSensitive" BOOLEAN      NOT NULL DEFAULT FALSE,
    "DefaultAction" VARCHAR(16)  NOT NULL DEFAULT 'block' CHECK ("DefaultAction" IN ('block', 'redact', 'warn')),
    "Enabled"       BOOLEAN      NOT NULL DEFAULT TRUE,
    "Version"       INT          NOT NULL DEFAULT 1,
    "CreatedAt"     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_blocklist_patterns_group
    ON aihub.blocklist_patterns("GroupId")
    WHERE "Enabled";

-- Função + triggers: dispara pg_notify no canal 'blocklist_changed' a cada
-- INSERT/UPDATE/DELETE em pattern_groups ou patterns. FOR EACH STATEMENT
-- (1 notify por comando, mesmo em batch update — suficiente, app refaz fetch
-- completo do catálogo no recv).
CREATE OR REPLACE FUNCTION aihub.notify_blocklist_changed() RETURNS TRIGGER AS $$
BEGIN
    PERFORM pg_notify('blocklist_changed', '');
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_blocklist_patterns_changed ON aihub.blocklist_patterns;
CREATE TRIGGER trg_blocklist_patterns_changed
    AFTER INSERT OR UPDATE OR DELETE ON aihub.blocklist_patterns
    FOR EACH STATEMENT
    EXECUTE FUNCTION aihub.notify_blocklist_changed();

DROP TRIGGER IF EXISTS trg_blocklist_groups_changed ON aihub.blocklist_pattern_groups;
CREATE TRIGGER trg_blocklist_groups_changed
    AFTER INSERT OR UPDATE OR DELETE ON aihub.blocklist_pattern_groups
    FOR EACH STATEMENT
    EXECUTE FUNCTION aihub.notify_blocklist_changed();

-- =============================================================================
-- 21. AVALIAÇÃO DE AGENTES — TEST SETS (header + versions imutáveis + cases)
--
-- Ver docs/adr/0015-evaluation-subsystem-architecture.md.
--
-- Padrão: header mutável + versions append-only com ContentHash idempotente
-- (mesmo de agent_versions/workflow_versions). Cases em tabela separada para
-- paginação na UI, FK em evaluation_results, e índice por tag pra subset eval.
--
-- Visibility alinhado com workflow_definitions (project|global). Default
-- 'project' — Visibility='global' exige permissão admin no controller.
--
-- ROLLBACK ORDER (em caso de necessidade — ver kill-switch operacional no
-- plano de implementação):
--   DROP VIEW evaluation_runs_with_progress;
--   DROP TABLE evaluation_results, evaluation_run_progress, evaluation_runs,
--              evaluator_config_versions, evaluator_configs,
--              evaluation_test_cases, evaluation_test_set_versions,
--              evaluation_test_sets;
--   ALTER TABLE agent_definitions DROP COLUMN "RegressionTestSetId",
--                                 DROP COLUMN "RegressionEvaluatorConfigVersionId",
--                                 DROP COLUMN "RegressionBudgetUsdCap";
--   ALTER TABLE llm_token_usage DROP COLUMN "Metadata";
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.evaluation_test_sets (
    "Id"               VARCHAR(64)  NOT NULL,
    "ProjectId"        VARCHAR(128) NOT NULL DEFAULT 'default',
    "Visibility"       VARCHAR(32)  NOT NULL DEFAULT 'project',  -- project | global
    "Name"             VARCHAR(256) NOT NULL,
    "Description"      VARCHAR(1024) NULL,
    "CurrentVersionId" VARCHAR(64)  NULL,                        -- aponta pra last Published
    "CreatedAt"        TIMESTAMPTZ  NOT NULL,
    "UpdatedAt"        TIMESTAMPTZ  NOT NULL,
    "CreatedBy"        VARCHAR(256) NULL,
    CONSTRAINT "PK_evaluation_test_sets" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_evaluation_test_sets_Visibility"
        CHECK ("Visibility" IN ('project', 'global'))
);

CREATE INDEX IF NOT EXISTS "IX_evaluation_test_sets_ProjectId"
    ON aihub.evaluation_test_sets ("ProjectId");

CREATE INDEX IF NOT EXISTS "IX_evaluation_test_sets_Visibility"
    ON aihub.evaluation_test_sets ("Visibility")
    WHERE "Visibility" = 'global';

CREATE TABLE IF NOT EXISTS aihub.evaluation_test_set_versions (
    "TestSetVersionId" VARCHAR(64)   NOT NULL,
    "TestSetId"        VARCHAR(64)   NOT NULL,
    "Revision"         INTEGER       NOT NULL,
    "Status"           VARCHAR(32)   NOT NULL,                   -- Draft | Published | Deprecated
    "ContentHash"      VARCHAR(128)  NOT NULL,
    "CreatedAt"        TIMESTAMPTZ   NOT NULL,
    "CreatedBy"        VARCHAR(256)  NULL,
    "ChangeReason"     VARCHAR(1024) NULL,
    CONSTRAINT "PK_evaluation_test_set_versions" PRIMARY KEY ("TestSetVersionId"),
    CONSTRAINT "FK_evaluation_test_set_versions_TestSetId"
        FOREIGN KEY ("TestSetId") REFERENCES aihub.evaluation_test_sets("Id") ON DELETE CASCADE,
    CONSTRAINT "CK_evaluation_test_set_versions_Status"
        CHECK ("Status" IN ('Draft', 'Published', 'Deprecated'))
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_evaluation_test_set_versions_TestSetId_Revision"
    ON aihub.evaluation_test_set_versions ("TestSetId", "Revision");

-- Idempotência: race em publish concorrente do mesmo conteúdo é no-op.
-- Excluindo Deprecated permite re-publish do mesmo conteúdo após deprecate.
CREATE UNIQUE INDEX IF NOT EXISTS "UX_evaluation_test_set_versions_TestSetId_ContentHash"
    ON aihub.evaluation_test_set_versions ("TestSetId", "ContentHash")
    WHERE "Status" != 'Deprecated';

CREATE INDEX IF NOT EXISTS "IX_evaluation_test_set_versions_TestSetId"
    ON aihub.evaluation_test_set_versions ("TestSetId");

CREATE TABLE IF NOT EXISTS aihub.evaluation_test_cases (
    "CaseId"             VARCHAR(64)  NOT NULL,
    "TestSetVersionId"   VARCHAR(64)  NOT NULL,
    "Index"              INTEGER      NOT NULL,
    "Input"              TEXT         NOT NULL,
    "ExpectedOutput"     TEXT         NULL,
    "ExpectedToolCalls"  JSONB        NULL,                      -- array de {name, argsSchema?}
    "Tags"               TEXT[]       NOT NULL DEFAULT '{}',
    "Weight"             DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    "CreatedAt"          TIMESTAMPTZ  NOT NULL,
    CONSTRAINT "PK_evaluation_test_cases" PRIMARY KEY ("CaseId"),
    CONSTRAINT "FK_evaluation_test_cases_TestSetVersionId"
        FOREIGN KEY ("TestSetVersionId") REFERENCES aihub.evaluation_test_set_versions("TestSetVersionId") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_evaluation_test_cases_TestSetVersionId_Index"
    ON aihub.evaluation_test_cases ("TestSetVersionId", "Index");

CREATE INDEX IF NOT EXISTS "IX_evaluation_test_cases_TestSetVersionId"
    ON aihub.evaluation_test_cases ("TestSetVersionId");

-- Subset eval por tag.
CREATE INDEX IF NOT EXISTS "IX_evaluation_test_cases_Tags"
    ON aihub.evaluation_test_cases USING GIN ("Tags");

-- =============================================================================
-- 22. AVALIAÇÃO DE AGENTES — EVALUATOR CONFIGS (header + versions imutáveis)
--
-- Header mutável (mesmo padrão de agent_definitions) + version append-only
-- com ContentHash idempotente. EvaluationRun pina EvaluatorConfigVersionId
-- (snapshot) — mudar bindings cria nova revision, não reescreve histórico.
--
-- Bindings: array JSONB de EvaluatorBinding {kind, name, params, enabled,
-- weight, bindingIndex}. Splitter como TEXT (mapeado para enum
-- SplitterStrategy em código). NumRepetitions=3 por default (Zheng et al.
-- 2023 — varianza de judge LLM ~0.1, n=1 mascara regressão).
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.evaluator_configs (
    "Id"                VARCHAR(64)  NOT NULL,
    "AgentDefinitionId" VARCHAR(256) NOT NULL,
    "Name"              VARCHAR(256) NOT NULL,
    "CurrentVersionId"  VARCHAR(64)  NULL,
    "CreatedAt"         TIMESTAMPTZ  NOT NULL,
    "UpdatedAt"         TIMESTAMPTZ  NOT NULL,
    "CreatedBy"         VARCHAR(256) NULL,
    CONSTRAINT "PK_evaluator_configs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_evaluator_configs_AgentDefinitionId"
        FOREIGN KEY ("AgentDefinitionId") REFERENCES aihub.agent_definitions("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_evaluator_configs_AgentDefinitionId"
    ON aihub.evaluator_configs ("AgentDefinitionId");

CREATE TABLE IF NOT EXISTS aihub.evaluator_config_versions (
    "EvaluatorConfigVersionId" VARCHAR(64)   NOT NULL,
    "EvaluatorConfigId"        VARCHAR(64)   NOT NULL,
    "Revision"                 INTEGER       NOT NULL,
    "Status"                   VARCHAR(32)   NOT NULL,           -- Draft | Published | Deprecated
    "ContentHash"              VARCHAR(128)  NOT NULL,
    "Bindings"                 JSONB         NOT NULL DEFAULT '[]', -- array de EvaluatorBinding
    "Splitter"                 VARCHAR(32)   NOT NULL DEFAULT 'LastTurn', -- LastTurn | Full | PerTurn
    "NumRepetitions"           INTEGER       NOT NULL DEFAULT 3,
    "CreatedAt"                TIMESTAMPTZ   NOT NULL,
    "CreatedBy"                VARCHAR(256)  NULL,
    "ChangeReason"             VARCHAR(1024) NULL,
    CONSTRAINT "PK_evaluator_config_versions" PRIMARY KEY ("EvaluatorConfigVersionId"),
    CONSTRAINT "FK_evaluator_config_versions_EvaluatorConfigId"
        FOREIGN KEY ("EvaluatorConfigId") REFERENCES aihub.evaluator_configs("Id") ON DELETE CASCADE,
    CONSTRAINT "CK_evaluator_config_versions_Status"
        CHECK ("Status" IN ('Draft', 'Published', 'Deprecated')),
    CONSTRAINT "CK_evaluator_config_versions_Splitter"
        CHECK ("Splitter" IN ('LastTurn', 'Full', 'PerTurn')),
    CONSTRAINT "CK_evaluator_config_versions_NumRepetitions"
        CHECK ("NumRepetitions" >= 1 AND "NumRepetitions" <= 10)
);

-- Cleanup do removido conceito de budget no evaluation (decisão arquitetural).
ALTER TABLE aihub.evaluator_config_versions
    DROP CONSTRAINT IF EXISTS "CK_evaluator_config_versions_BudgetUsdCap";
ALTER TABLE aihub.evaluator_config_versions
    DROP COLUMN IF EXISTS "BudgetUsdCap";

CREATE UNIQUE INDEX IF NOT EXISTS "UX_evaluator_config_versions_ConfigId_Revision"
    ON aihub.evaluator_config_versions ("EvaluatorConfigId", "Revision");

CREATE INDEX IF NOT EXISTS "IX_evaluator_config_versions_EvaluatorConfigId"
    ON aihub.evaluator_config_versions ("EvaluatorConfigId");

CREATE INDEX IF NOT EXISTS "IX_evaluator_config_versions_ContentHash"
    ON aihub.evaluator_config_versions ("ContentHash");

-- =============================================================================
-- 23. AVALIAÇÃO DE AGENTES — RUNS + PROGRESS (contadores rolling em tabela
--     auxiliar para evitar hot row contention).
--
-- evaluation_runs é o header pinado: AgentVersionId + TestSetVersionId +
-- EvaluatorConfigVersionId fazem dela reproducível. BaselineRunId aponta
-- pra última run Completed no mesmo tuple (rastreabilidade de regressão).
--
-- evaluation_run_progress: contadores rolling em tabela separada — INSERT
-- ON CONFLICT DO UPDATE col = col + EXCLUDED.col reduz lock contention ~90%
-- vs UPDATE evaluation_runs SET cases_completed = cases_completed + 1.
--
-- Idempotência do autotrigger: unique index parcial em (AgentVersionId)
-- WHERE TriggerSource='AgentVersionPublished' AND Status IN ('Pending',
-- 'Running', 'Completed') — re-publish da mesma version é no-op.
--
-- LastHeartbeatAt: usado pelo EvaluationReaperService (PR 2) para marcar
-- runs Running sem heartbeat há > 5min como Failed (stale recovery).
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.evaluation_runs (
    "RunId"                      VARCHAR(64)   NOT NULL,
    "ProjectId"                  VARCHAR(128)  NOT NULL DEFAULT 'default',
    "AgentDefinitionId"          VARCHAR(256)  NOT NULL,
    "AgentVersionId"             VARCHAR(64)   NOT NULL,         -- snapshot pinado
    "TestSetVersionId"           VARCHAR(64)   NOT NULL,         -- snapshot pinado
    "EvaluatorConfigVersionId"   VARCHAR(64)   NOT NULL,         -- snapshot pinado
    "BaselineRunId"              VARCHAR(64)   NULL,             -- última Completed no mesmo tuple
    "Status"                     VARCHAR(32)   NOT NULL DEFAULT 'Pending',
    "Priority"                   INTEGER       NOT NULL DEFAULT 0, -- Manual=0, AgentVersionPublished=10
    "TriggeredBy"                VARCHAR(256)  NULL,             -- userId nullable em autotrigger
    "TriggerSource"              VARCHAR(32)   NOT NULL,         -- Manual | AgentVersionPublished | ApiClient
    "TriggerContext"             JSONB         NULL,             -- {agent_version_id, published_by, foundry_endpoint_snapshot}
    "ExecutionId"                VARCHAR(128)  NOT NULL,         -- "eval:{RunId}"
    "CasesTotal"                 INTEGER       NOT NULL DEFAULT 0,
    "StartedAt"                  TIMESTAMPTZ   NULL,
    "CompletedAt"                TIMESTAMPTZ   NULL,
    "LastHeartbeatAt"            TIMESTAMPTZ   NULL,
    "LastError"                  VARCHAR(2048) NULL,
    "CreatedAt"                  TIMESTAMPTZ   NOT NULL,
    CONSTRAINT "PK_evaluation_runs" PRIMARY KEY ("RunId"),
    CONSTRAINT "FK_evaluation_runs_AgentVersionId"
        FOREIGN KEY ("AgentVersionId") REFERENCES aihub.agent_versions("AgentVersionId"),
    CONSTRAINT "FK_evaluation_runs_TestSetVersionId"
        FOREIGN KEY ("TestSetVersionId") REFERENCES aihub.evaluation_test_set_versions("TestSetVersionId"),
    CONSTRAINT "FK_evaluation_runs_EvaluatorConfigVersionId"
        FOREIGN KEY ("EvaluatorConfigVersionId") REFERENCES aihub.evaluator_config_versions("EvaluatorConfigVersionId"),
    CONSTRAINT "FK_evaluation_runs_BaselineRunId"
        FOREIGN KEY ("BaselineRunId") REFERENCES aihub.evaluation_runs("RunId"),
    CONSTRAINT "CK_evaluation_runs_Status"
        CHECK ("Status" IN ('Pending', 'Running', 'Completed', 'Failed', 'Cancelled')),
    CONSTRAINT "CK_evaluation_runs_TriggerSource"
        CHECK ("TriggerSource" IN ('Manual', 'AgentVersionPublished', 'ApiClient'))
);

CREATE INDEX IF NOT EXISTS "IX_evaluation_runs_AgentDefinitionId_CreatedAt"
    ON aihub.evaluation_runs ("AgentDefinitionId", "CreatedAt" DESC);

CREATE INDEX IF NOT EXISTS "IX_evaluation_runs_Status_Priority_CreatedAt"
    ON aihub.evaluation_runs ("Status", "Priority", "CreatedAt")
    WHERE "Status" IN ('Pending', 'Running');

CREATE INDEX IF NOT EXISTS "IX_evaluation_runs_LastHeartbeatAt"
    ON aihub.evaluation_runs ("LastHeartbeatAt")
    WHERE "Status" = 'Running';

CREATE INDEX IF NOT EXISTS "IX_evaluation_runs_ProjectId"
    ON aihub.evaluation_runs ("ProjectId");

-- Idempotência do autotrigger: re-publish da mesma AgentVersion é no-op.
-- Cancelled e Failed ficam de fora (permite re-trigger após falha).
CREATE UNIQUE INDEX IF NOT EXISTS "UX_evaluation_runs_Autotrigger"
    ON aihub.evaluation_runs ("AgentVersionId")
    WHERE "TriggerSource" = 'AgentVersionPublished'
      AND "Status" IN ('Pending', 'Running', 'Completed');

CREATE TABLE IF NOT EXISTS aihub.evaluation_run_progress (
    "RunId"          VARCHAR(64)   NOT NULL,
    "CasesCompleted" INTEGER       NOT NULL DEFAULT 0,
    "CasesPassed"    INTEGER       NOT NULL DEFAULT 0,
    "CasesFailed"    INTEGER       NOT NULL DEFAULT 0,
    "AvgScore"       NUMERIC(5,4)  NULL,                         -- 0..1
    "TotalCostUsd"   NUMERIC(12,6) NOT NULL DEFAULT 0,
    "TotalTokens"    BIGINT        NOT NULL DEFAULT 0,
    "LastUpdated"    TIMESTAMPTZ   NOT NULL,
    CONSTRAINT "PK_evaluation_run_progress" PRIMARY KEY ("RunId"),
    CONSTRAINT "FK_evaluation_run_progress_RunId"
        FOREIGN KEY ("RunId") REFERENCES aihub.evaluation_runs("RunId") ON DELETE CASCADE
);

-- =============================================================================
-- 24. AVALIAÇÃO DE AGENTES — RESULTS (1:N por case+evaluator+binding+repetition)
--
-- PK composta com BindingIndex permite o mesmo evaluator (ex.: KeywordCheck)
-- declarado 2x na config com keyword sets diferentes — sem colisão.
--
-- JudgeModel registrado para detecção de self-enhancement bias (banner UI
-- alerta quando judge_model e agent_model pertencem à mesma família).
--
-- OutputContent truncado a 8KB (mesmo limite do TokenTrackingChatClient).
-- Output integral em llm_token_usage.OutputContent correlacionado por
-- ExecutionId='eval:{RunId}'.
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.evaluation_results (
    "ResultId"           VARCHAR(64)   NOT NULL,
    "RunId"              VARCHAR(64)   NOT NULL,
    "CaseId"             VARCHAR(64)   NOT NULL,
    "EvaluatorName"      VARCHAR(128)  NOT NULL,
    "BindingIndex"       INTEGER       NOT NULL DEFAULT 0,
    "RepetitionIndex"    INTEGER       NOT NULL DEFAULT 0,
    "Score"              NUMERIC(5,4)  NULL,                     -- 0..1
    "Passed"             BOOLEAN       NOT NULL DEFAULT FALSE,
    "Reason"             TEXT          NULL,                     -- explicação do judge
    "OutputContent"      TEXT          NULL,                     -- truncado 8KB
    "JudgeModel"         VARCHAR(128)  NULL,                     -- ex.: gpt-4o, claude-sonnet-4
    "LatencyMs"          DOUBLE PRECISION NULL,
    "CostUsd"            NUMERIC(12,6) NULL,
    "InputTokens"        INTEGER       NULL,
    "OutputTokens"       INTEGER       NULL,
    "EvaluatorMetadata"  JSONB         NULL,                     -- payload bruto MEAI/Foundry
    "CreatedAt"          TIMESTAMPTZ   NOT NULL,
    CONSTRAINT "PK_evaluation_results" PRIMARY KEY ("RunId", "CaseId", "EvaluatorName", "BindingIndex", "RepetitionIndex"),
    CONSTRAINT "FK_evaluation_results_RunId"
        FOREIGN KEY ("RunId") REFERENCES aihub.evaluation_runs("RunId") ON DELETE CASCADE,
    CONSTRAINT "FK_evaluation_results_CaseId"
        FOREIGN KEY ("CaseId") REFERENCES aihub.evaluation_test_cases("CaseId")
);

CREATE INDEX IF NOT EXISTS "IX_evaluation_results_RunId"
    ON aihub.evaluation_results ("RunId");

CREATE INDEX IF NOT EXISTS "IX_evaluation_results_RunId_Passed"
    ON aihub.evaluation_results ("RunId", "Passed");

CREATE INDEX IF NOT EXISTS "IX_evaluation_results_CaseId"
    ON aihub.evaluation_results ("CaseId");

-- ResultId não é PK por si só (PK composta cobre unicidade) mas usado em
-- referências externas (ex.: link direto pra row no UI). Unique adicional.
CREATE UNIQUE INDEX IF NOT EXISTS "UX_evaluation_results_ResultId"
    ON aihub.evaluation_results ("ResultId");

-- =============================================================================
-- 25. AVALIAÇÃO DE AGENTES — VIEW agregada (read path)
--
-- Read path da UI faz JOIN com run_progress pra ler contadores rolling sem
-- bater na hot row do evaluation_runs.
-- =============================================================================

-- DROP necessário pra remover a coluna BudgetUsdCap removida em 25.x
-- (CREATE OR REPLACE não permite drop de colunas).
DROP VIEW IF EXISTS aihub.evaluation_runs_with_progress;
CREATE VIEW aihub.evaluation_runs_with_progress AS
SELECT
    r."RunId",
    r."ProjectId",
    r."AgentDefinitionId",
    r."AgentVersionId",
    r."TestSetVersionId",
    r."EvaluatorConfigVersionId",
    r."BaselineRunId",
    r."Status",
    r."Priority",
    r."TriggeredBy",
    r."TriggerSource",
    r."TriggerContext",
    r."ExecutionId",
    r."CasesTotal",
    r."StartedAt",
    r."CompletedAt",
    r."LastHeartbeatAt",
    r."LastError",
    r."CreatedAt",
    COALESCE(p."CasesCompleted", 0) AS "CasesCompleted",
    COALESCE(p."CasesPassed",    0) AS "CasesPassed",
    COALESCE(p."CasesFailed",    0) AS "CasesFailed",
    p."AvgScore",
    COALESCE(p."TotalCostUsd",   0) AS "TotalCostUsd",
    COALESCE(p."TotalTokens",    0) AS "TotalTokens",
    p."LastUpdated"                 AS "ProgressLastUpdated"
FROM aihub.evaluation_runs r
LEFT JOIN aihub.evaluation_run_progress p ON p."RunId" = r."RunId";

-- =============================================================================
-- 26. AVALIAÇÃO DE AGENTES — extensão de agent_definitions (regression config)
--
-- Colunas opcionais para autotrigger em publish de AgentVersion. Quando
-- RegressionTestSetId IS NULL, autotrigger é no-op (warning UI, sem block).
-- Todas NULLABLE para safe rolling deploy (instâncias antigas sem mapping
-- ignoram colunas).
-- =============================================================================

ALTER TABLE aihub.agent_definitions
    ADD COLUMN IF NOT EXISTS "RegressionTestSetId" VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS "RegressionEvaluatorConfigVersionId" VARCHAR(64) NULL;

-- Cleanup do removido conceito de budget no evaluation (decisão arquitetural).
ALTER TABLE aihub.agent_definitions
    DROP COLUMN IF EXISTS "RegressionBudgetUsdCap";

-- Drop também a coluna na evaluation_runs.
ALTER TABLE aihub.evaluation_runs
    DROP COLUMN IF EXISTS "BudgetUsdCap";

-- FKs adicionadas após colunas (idempotente — DO $$ ... $$ guard contra duplicar
-- constraint quando schemas.sql é re-aplicado).
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'FK_agent_definitions_RegressionTestSetId'
    ) THEN
        ALTER TABLE aihub.agent_definitions
            ADD CONSTRAINT "FK_agent_definitions_RegressionTestSetId"
            FOREIGN KEY ("RegressionTestSetId")
            REFERENCES aihub.evaluation_test_sets("Id")
            ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'FK_agent_definitions_RegressionEvaluatorConfigVersionId'
    ) THEN
        ALTER TABLE aihub.agent_definitions
            ADD CONSTRAINT "FK_agent_definitions_RegressionEvaluatorConfigVersionId"
            FOREIGN KEY ("RegressionEvaluatorConfigVersionId")
            REFERENCES aihub.evaluator_config_versions("EvaluatorConfigVersionId")
            ON DELETE SET NULL;
    END IF;
END $$;

-- =============================================================================
-- 27. AVALIAÇÃO DE AGENTES — extensão de llm_token_usage (metadata genérico)
--
-- Coluna metadata JSONB para tagging cross-cutting. Eval persiste com
-- {"source":"evaluation","run_id":"..."} para correlação. Outros usos
-- futuros (replay, sandbox flag explícito) cabem aqui sem ALTER novo.
-- =============================================================================

ALTER TABLE aihub.llm_token_usage
    ADD COLUMN IF NOT EXISTS "Metadata" JSONB NULL;

CREATE INDEX IF NOT EXISTS "IX_llm_token_usage_Metadata_source"
    ON aihub.llm_token_usage (("Metadata"->>'source'))
    WHERE "Metadata" IS NOT NULL;
