-- =============================================================================
-- EfsAiHub — Schema DDL
-- PostgreSQL 16+ · Schema: aihub
--
-- Uso:
--   psql -U <usuario> -d <banco> -f schema.sql
--
-- Este arquivo é idempotente: pode ser executado múltiplas vezes sem erros.
-- Para recriar do zero, execute schema_drop.sql antes deste.
--
-- Convenções:
--   - Todas as tabelas ficam no schema aihub (não public)
--   - Timestamps sempre em UTC (TIMESTAMPTZ)
--   - PKs string usam VARCHAR com limite explícito
--   - PKs numéricas usam GENERATED BY DEFAULT AS IDENTITY
--   - JSONB para payloads semi-estruturados
--   - BYTEA para dados binários (checkpoints)
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS aihub;

SET search_path TO aihub;

-- =============================================================================
-- 1. PROJETOS (multi-tenant)
-- =============================================================================

-- Nota: projects usa colunas lowercase (sem aspas) para compatibilidade com
-- PgProjectRepository que executa raw SQL (ex: WHERE tenant_id = @tenantId).
CREATE TABLE IF NOT EXISTS aihub.projects (
    id          VARCHAR(128)  NOT NULL,
    name        VARCHAR(256)  NOT NULL,
    tenant_id   VARCHAR(128)  NOT NULL,
    description VARCHAR(1024) NULL,
    settings    JSONB         NOT NULL DEFAULT '{}',
    llm_config  JSONB         NULL,                     -- override de modelo por projeto
    budget      JSONB         NULL,                     -- limites de custo/tokens por projeto
    created_at  TIMESTAMPTZ   NOT NULL,
    updated_at  TIMESTAMPTZ   NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ix_projects_tenant_id
    ON aihub.projects (tenant_id);

-- =============================================================================
-- 2. DEFINIÇÕES DE AGENTES E WORKFLOWS
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.agent_definitions (
    "Id"         VARCHAR(256) NOT NULL,
    "Name"       VARCHAR(512) NOT NULL,
    "Data"       TEXT         NOT NULL,                 -- JSON serializado do AgentDef
    "ProjectId"  VARCHAR(128) NOT NULL DEFAULT 'default',
    "CreatedAt"  TIMESTAMPTZ  NOT NULL,
    "UpdatedAt"  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT "PK_agent_definitions" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS aihub.workflow_definitions (
    "Id"         VARCHAR(256) NOT NULL,
    "Name"       VARCHAR(512) NOT NULL,
    "Data"       TEXT         NOT NULL,                 -- JSON serializado do WorkflowDef
    "ProjectId"  VARCHAR(128) NOT NULL DEFAULT 'default',
    "Visibility" VARCHAR(32)  NOT NULL DEFAULT 'project', -- project | global
    "CreatedAt"  TIMESTAMPTZ  NOT NULL,
    "UpdatedAt"  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT "PK_workflow_definitions" PRIMARY KEY ("Id")
);

-- =============================================================================
-- 3. VERSIONAMENTO DE AGENTES E WORKFLOWS (snapshots imutáveis)
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.agent_versions (
    "AgentVersionId"    VARCHAR(64)   NOT NULL,
    "AgentDefinitionId" VARCHAR(256)  NOT NULL,
    "Revision"          INTEGER       NOT NULL,
    "CreatedAt"         TIMESTAMPTZ   NOT NULL,
    "CreatedBy"         VARCHAR(256)  NULL,
    "ChangeReason"      VARCHAR(1024) NULL,
    "Status"            VARCHAR(32)   NOT NULL,         -- Draft | Published | Deprecated
    "ContentHash"       VARCHAR(128)  NOT NULL,
    "Snapshot"          JSONB         NOT NULL,         -- snapshot completo do agente no momento do publish
    CONSTRAINT "PK_agent_versions" PRIMARY KEY ("AgentVersionId")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_agent_versions_AgentDefinitionId_Revision"
    ON aihub.agent_versions ("AgentDefinitionId", "Revision");

CREATE INDEX IF NOT EXISTS "IX_agent_versions_AgentDefinitionId"
    ON aihub.agent_versions ("AgentDefinitionId");

CREATE INDEX IF NOT EXISTS "IX_agent_versions_ContentHash"
    ON aihub.agent_versions ("ContentHash");

CREATE TABLE IF NOT EXISTS aihub.workflow_versions (
    "WorkflowVersionId"    VARCHAR(64)   NOT NULL,
    "WorkflowDefinitionId" VARCHAR(256)  NOT NULL,
    "Revision"             INTEGER       NOT NULL,
    "CreatedAt"            TIMESTAMPTZ   NOT NULL,
    "CreatedBy"            VARCHAR(256)  NULL,
    "ChangeReason"         VARCHAR(1024) NULL,
    "Status"               VARCHAR(32)   NOT NULL,
    "ContentHash"          VARCHAR(128)  NOT NULL,
    "Snapshot"             JSONB         NOT NULL,
    CONSTRAINT "PK_workflow_versions" PRIMARY KEY ("WorkflowVersionId")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_workflow_versions_WorkflowDefinitionId_Revision"
    ON aihub.workflow_versions ("WorkflowDefinitionId", "Revision");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_workflow_versions_WorkflowDefinitionId_ContentHash"
    ON aihub.workflow_versions ("WorkflowDefinitionId", "ContentHash");

CREATE INDEX IF NOT EXISTS "IX_workflow_versions_WorkflowDefinitionId"
    ON aihub.workflow_versions ("WorkflowDefinitionId");

-- =============================================================================
-- 4. VERSIONAMENTO DE PROMPTS
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.agent_prompt_versions (
    "RowId"     INTEGER      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "AgentId"   VARCHAR(256) NOT NULL,
    "VersionId" VARCHAR(128) NOT NULL,
    "Content"   TEXT         NOT NULL,
    "IsActive"  BOOLEAN      NOT NULL,
    "CreatedAt" TIMESTAMPTZ  NOT NULL,
    CONSTRAINT "PK_agent_prompt_versions" PRIMARY KEY ("RowId")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_agent_prompt_versions_AgentId_VersionId"
    ON aihub.agent_prompt_versions ("AgentId", "VersionId");

CREATE INDEX IF NOT EXISTS "IX_agent_prompt_versions_AgentId"
    ON aihub.agent_prompt_versions ("AgentId");

-- =============================================================================
-- 5. SKILLS (reutilizáveis entre agentes)
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.skills (
    "Id"          VARCHAR(256) NOT NULL,
    "Name"        VARCHAR(256) NOT NULL,
    "Data"        JSONB        NOT NULL,
    "ContentHash" VARCHAR(128) NOT NULL,
    "CreatedAt"   TIMESTAMPTZ  NOT NULL,
    "UpdatedAt"   TIMESTAMPTZ  NOT NULL,
    "ProjectId"   VARCHAR(128) NOT NULL DEFAULT 'default',
    CONSTRAINT "PK_skills" PRIMARY KEY ("Id")
);

-- Garante coluna em bancos existentes (idempotente)
ALTER TABLE aihub.skills
    ADD COLUMN IF NOT EXISTS "ProjectId" VARCHAR(128) NOT NULL DEFAULT 'default';

CREATE INDEX IF NOT EXISTS "IX_skills_ProjectId" ON aihub.skills ("ProjectId");

CREATE TABLE IF NOT EXISTS aihub.skill_versions (
    "SkillVersionId" VARCHAR(64)   NOT NULL,
    "SkillId"        VARCHAR(256)  NOT NULL,
    "Revision"       INTEGER       NOT NULL,
    "CreatedAt"      TIMESTAMPTZ   NOT NULL,
    "CreatedBy"      VARCHAR(256)  NULL,
    "ChangeReason"   VARCHAR(1024) NULL,
    "ContentHash"    VARCHAR(128)  NOT NULL,
    "Snapshot"       JSONB         NOT NULL,
    CONSTRAINT "PK_skill_versions" PRIMARY KEY ("SkillVersionId")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_skill_versions_SkillId_Revision"
    ON aihub.skill_versions ("SkillId", "Revision");

CREATE INDEX IF NOT EXISTS "IX_skill_versions_SkillId"
    ON aihub.skill_versions ("SkillId");

CREATE INDEX IF NOT EXISTS "IX_skill_versions_ContentHash"
    ON aihub.skill_versions ("ContentHash");

-- =============================================================================
-- 5.1 MCP SERVERS (Model Context Protocol — registry centralizado)
-- =============================================================================
-- Agents referenciam servidores MCP pelo Id deste registro. A coluna Data
-- JSONB guarda o McpServer completo (ServerLabel, ServerUrl, AllowedTools,
-- Headers, RequireApproval, Description). Project-scoped.

CREATE TABLE IF NOT EXISTS aihub.mcp_servers (
    "Id"         VARCHAR(128) NOT NULL,
    "Name"       VARCHAR(256) NOT NULL,
    "Data"       JSONB        NOT NULL,
    "ProjectId"  VARCHAR(128) NOT NULL DEFAULT 'default',
    "CreatedAt"  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "UpdatedAt"  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_mcp_servers" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_mcp_servers_ProjectId_Name"
    ON aihub.mcp_servers ("ProjectId", "Name");

-- =============================================================================
-- 6. EXECUÇÕES DE WORKFLOW
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.workflow_executions (
    "ExecutionId" VARCHAR(128) NOT NULL,
    "WorkflowId"  VARCHAR(256) NOT NULL,
    "ProjectId"   VARCHAR(128) NOT NULL DEFAULT 'default',
    "Status"      VARCHAR(32)  NOT NULL,                -- Pending | Running | Completed | Failed | Cancelled
    "Data"        TEXT         NOT NULL,
    "StartedAt"   TIMESTAMPTZ  NOT NULL,
    "CompletedAt" TIMESTAMPTZ  NULL,
    CONSTRAINT "PK_workflow_executions" PRIMARY KEY ("ExecutionId")
);

CREATE INDEX IF NOT EXISTS "IX_workflow_executions_WorkflowId"
    ON aihub.workflow_executions ("WorkflowId");

CREATE INDEX IF NOT EXISTS "IX_workflow_executions_Status"
    ON aihub.workflow_executions ("Status");

CREATE INDEX IF NOT EXISTS "IX_workflow_executions_StartedAt"
    ON aihub.workflow_executions ("StartedAt");

CREATE INDEX IF NOT EXISTS "IX_workflow_executions_WorkflowId_Status_StartedAt"
    ON aihub.workflow_executions ("WorkflowId", "Status", "StartedAt" DESC);

-- =============================================================================
-- 7. NÓS DE EXECUÇÃO (Graph mode)
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.node_executions (
    "RowId"       INTEGER      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ExecutionId" VARCHAR(128) NOT NULL,
    "NodeId"      VARCHAR(256) NOT NULL,
    "Data"        TEXT         NOT NULL,
    "ProjectId"   VARCHAR(128) NULL,  -- F4 — boundary de isolamento (ADR 003)
    CONSTRAINT "PK_node_executions" PRIMARY KEY ("RowId")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_node_executions_ExecutionId_NodeId"
    ON aihub.node_executions ("ExecutionId", "NodeId");

CREATE INDEX IF NOT EXISTS "IX_node_executions_ExecutionId"
    ON aihub.node_executions ("ExecutionId");

CREATE INDEX IF NOT EXISTS ix_node_executions_project_exec
    ON aihub.node_executions ("ProjectId", "ExecutionId");

-- =============================================================================
-- 8. CHECKPOINTS DE WORKFLOW
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.workflow_checkpoints (
    "ExecutionId" VARCHAR(128) NOT NULL,
    "Data"        BYTEA        NOT NULL,                -- estado serializado binário
    "UpdatedAt"   TIMESTAMPTZ  NOT NULL,
    CONSTRAINT "PK_workflow_checkpoints" PRIMARY KEY ("ExecutionId")
);

-- =============================================================================
-- 9. AUDITORIA DE EVENTOS DE WORKFLOW
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.workflow_event_audit (
    "Id"          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ExecutionId" VARCHAR(128) NOT NULL,
    "EventType"   VARCHAR(64)  NOT NULL,
    "Payload"     TEXT         NOT NULL,
    "Timestamp"   TIMESTAMPTZ  NOT NULL,
    CONSTRAINT "PK_workflow_event_audit" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_workflow_event_audit_ExecutionId"
    ON aihub.workflow_event_audit ("ExecutionId");

CREATE INDEX IF NOT EXISTS "IX_workflow_event_audit_ExecutionId_Id"
    ON aihub.workflow_event_audit ("ExecutionId", "Id");

CREATE INDEX IF NOT EXISTS "IX_workflow_event_audit_Timestamp"
    ON aihub.workflow_event_audit ("Timestamp");

-- Trilha de auditoria de mudanças CRUD em recursos administrativos
-- (Project, Agent, Workflow, Skill, ModelPricing). Escrita pelos controllers
-- Admin via IAdminAuditLogger. Retention: AuditRetentionDays (default 90).
CREATE TABLE IF NOT EXISTS aihub.admin_audit_log (
    "Id"            BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "TenantId"      VARCHAR(128) NULL,
    "ProjectId"     VARCHAR(128) NULL,
    "ActorUserId"   VARCHAR(128) NOT NULL,
    "ActorUserType" VARCHAR(32)  NULL,
    "Action"        VARCHAR(32)  NOT NULL,
    "ResourceType"  VARCHAR(64)  NOT NULL,
    "ResourceId"    VARCHAR(128) NOT NULL,
    "PayloadBefore" JSONB        NULL,
    "PayloadAfter"  JSONB        NULL,
    "Timestamp"     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_admin_audit_log" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_admin_audit_log_TenantId_Timestamp"
    ON aihub.admin_audit_log ("TenantId", "Timestamp" DESC);

CREATE INDEX IF NOT EXISTS "IX_admin_audit_log_ResourceType_ResourceId"
    ON aihub.admin_audit_log ("ResourceType", "ResourceId");

CREATE INDEX IF NOT EXISTS "IX_admin_audit_log_ActorUserId_Timestamp"
    ON aihub.admin_audit_log ("ActorUserId", "Timestamp" DESC);

-- =============================================================================
-- 10. CONVERSAS E MENSAGENS (Chat)
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.conversations (
    "ConversationId"    VARCHAR(64)  NOT NULL,
    "UserId"            VARCHAR(256) NOT NULL,
    "UserType"          TEXT         NULL,
    "WorkflowId"        VARCHAR(256) NOT NULL,
    "Title"             VARCHAR(512) NULL,
    "ActiveExecutionId" VARCHAR(64)  NULL,
    "LastActiveAgentId" VARCHAR(256) NULL,
    "ContextClearedAt"  TIMESTAMPTZ  NULL,
    "ProjectId"         VARCHAR(128) NOT NULL DEFAULT 'default',
    "CreatedAt"         TIMESTAMPTZ  NOT NULL,
    "LastMessageAt"     TIMESTAMPTZ  NOT NULL,
    "Metadata"          JSONB        NOT NULL DEFAULT '{}',
    CONSTRAINT "PK_conversations" PRIMARY KEY ("ConversationId")
);

CREATE INDEX IF NOT EXISTS "IX_conversations_UserId"
    ON aihub.conversations ("UserId");

CREATE INDEX IF NOT EXISTS "IX_conversations_LastMessageAt"
    ON aihub.conversations ("LastMessageAt");

CREATE TABLE IF NOT EXISTS aihub.chat_messages (
    "MessageId"        VARCHAR(64)  NOT NULL,
    "ConversationId"   VARCHAR(64)  NOT NULL,
    "Role"             VARCHAR(32)  NOT NULL,           -- user | assistant | system | tool
    "Content"          TEXT         NOT NULL,
    "StructuredOutput" JSONB        NULL,
    "CreatedAt"        TIMESTAMPTZ  NOT NULL,
    "TokenCount"       INTEGER      NOT NULL,
    "ExecutionId"      VARCHAR(64)  NULL,
    CONSTRAINT "PK_chat_messages" PRIMARY KEY ("MessageId")
);

CREATE INDEX IF NOT EXISTS "IX_chat_messages_ConversationId"
    ON aihub.chat_messages ("ConversationId");

CREATE INDEX IF NOT EXISTS "IX_chat_messages_ConversationId_CreatedAt"
    ON aihub.chat_messages ("ConversationId", "CreatedAt");

-- =============================================================================
-- 11. INTERAÇÕES HUMANAS (HITL — Human-in-the-Loop)
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.human_interactions (
    "InteractionId" VARCHAR(128) NOT NULL,
    "ExecutionId"   VARCHAR(128) NOT NULL,
    "WorkflowId"    VARCHAR(256) NOT NULL,
    "Prompt"        TEXT         NOT NULL,
    "Context"       TEXT         NULL,
    "InteractionType" VARCHAR(32) NOT NULL DEFAULT 'Approval', -- Approval | Input | Choice
    "Options"       TEXT         NULL,                  -- JSON array de opções (ex: ["Confirmar","Cancelar"])
    "Status"        VARCHAR(32)  NOT NULL,              -- Pending | Approved | Rejected | Expired
    "Resolution"    TEXT         NULL,
    "CreatedAt"     TIMESTAMPTZ  NOT NULL,
    "ResolvedAt"    TIMESTAMPTZ  NULL,
    "ResolvedBy"    VARCHAR(128) NULL,                  -- UserId de quem resolveu; 'system:timeout' para expiração automática
    CONSTRAINT "PK_human_interactions" PRIMARY KEY ("InteractionId")
);

CREATE INDEX IF NOT EXISTS "IX_human_interactions_ExecutionId"
    ON aihub.human_interactions ("ExecutionId");

CREATE INDEX IF NOT EXISTS "IX_human_interactions_Status"
    ON aihub.human_interactions ("Status");

-- Auditoria: "minhas resoluções HITL" — queries por quem resolveu em dado período.
CREATE INDEX IF NOT EXISTS "IX_human_interactions_ResolvedBy_ResolvedAt"
    ON aihub.human_interactions ("ResolvedBy", "ResolvedAt" DESC)
    WHERE "ResolvedBy" IS NOT NULL;

-- =============================================================================
-- 12. SESSÕES DE AGENTE
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.agent_sessions (
    "SessionId"       VARCHAR(128) NOT NULL,
    "AgentId"         VARCHAR(256) NOT NULL,
    "SerializedState" TEXT         NOT NULL,
    "TurnCount"       INTEGER      NOT NULL DEFAULT 0,
    "CreatedAt"       TIMESTAMPTZ  NOT NULL,
    "LastAccessedAt"  TIMESTAMPTZ  NOT NULL,
    "ExpiresAt"       TIMESTAMPTZ  NOT NULL,
    CONSTRAINT "PK_agent_sessions" PRIMARY KEY ("SessionId")
);

CREATE INDEX IF NOT EXISTS "IX_agent_sessions_AgentId"
    ON aihub.agent_sessions ("AgentId");

CREATE INDEX IF NOT EXISTS "IX_agent_sessions_ExpiresAt"
    ON aihub.agent_sessions ("ExpiresAt");

-- =============================================================================
-- 13. JOBS DE BACKGROUND (respostas assíncronas de agentes)
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.background_response_jobs (
    "JobId"           VARCHAR(64)  NOT NULL,
    "AgentId"         VARCHAR(256) NOT NULL,
    "AgentVersionId"  VARCHAR(64)  NULL,
    "SessionId"       VARCHAR(128) NULL,
    "Input"           TEXT         NOT NULL,
    "Status"          VARCHAR(32)  NOT NULL,            -- Queued | Running | Completed | Failed
    "Output"          TEXT         NULL,
    "LastError"       TEXT         NULL,
    "Attempt"         INTEGER      NOT NULL DEFAULT 0,
    "CallbackTarget"  JSONB        NULL,
    "IdempotencyKey"  VARCHAR(128) NULL,
    "CreatedAt"       TIMESTAMPTZ  NOT NULL,
    "StartedAt"       TIMESTAMPTZ  NULL,
    "CompletedAt"     TIMESTAMPTZ  NULL,
    CONSTRAINT "PK_background_response_jobs" PRIMARY KEY ("JobId")
);

CREATE INDEX IF NOT EXISTS "IX_background_response_jobs_Status_CreatedAt"
    ON aihub.background_response_jobs ("Status", "CreatedAt");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_background_response_jobs_IdempotencyKey"
    ON aihub.background_response_jobs ("IdempotencyKey")
    WHERE "IdempotencyKey" IS NOT NULL;

-- =============================================================================
-- 14. OBSERVABILIDADE — USO DE TOKENS LLM
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.llm_token_usage (
    "Id"              BIGINT           NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "AgentId"         VARCHAR(256)     NOT NULL,
    "ModelId"         VARCHAR(256)     NOT NULL,
    "ExecutionId"     VARCHAR(128)     NULL,
    "WorkflowId"      VARCHAR(256)     NULL,
    "InputTokens"     INTEGER          NOT NULL,
    "OutputTokens"    INTEGER          NOT NULL,
    "TotalTokens"     INTEGER          NOT NULL,
    "CachedTokens"    INTEGER          NOT NULL DEFAULT 0,  -- F1 — OpenAI prompt cache hits
    "DurationMs"      DOUBLE PRECISION NOT NULL,
    "PromptVersionId" VARCHAR(128)     NULL,
    "AgentVersionId"  VARCHAR(64)      NULL,  -- rastreia snapshot do agente na execução
    "OutputContent"   TEXT             NULL,
    "RetryCount"      INTEGER          NOT NULL DEFAULT 0,
    "ProjectId"       VARCHAR(128)     NULL,  -- F4 — boundary de isolamento (ADR 003)
    "CreatedAt"       TIMESTAMPTZ      NOT NULL,
    CONSTRAINT "PK_llm_token_usage" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_llm_token_usage_AgentId"
    ON aihub.llm_token_usage ("AgentId");

CREATE INDEX IF NOT EXISTS "IX_llm_token_usage_ExecutionId"
    ON aihub.llm_token_usage ("ExecutionId");

CREATE INDEX IF NOT EXISTS "IX_llm_token_usage_CreatedAt"
    ON aihub.llm_token_usage ("CreatedAt");

CREATE INDEX IF NOT EXISTS ix_llm_token_usage_project_created
    ON aihub.llm_token_usage ("ProjectId", "CreatedAt" DESC);

-- =============================================================================
-- 15. OBSERVABILIDADE — INVOCAÇÕES DE TOOLS
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.tool_invocations (
    "Id"           BIGINT           NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ExecutionId"  VARCHAR(128)     NOT NULL,
    "AgentId"      VARCHAR(256)     NOT NULL,
    "ToolName"     VARCHAR(256)     NOT NULL,
    "Arguments"    JSONB            NULL,
    "Result"       TEXT             NULL,
    "DurationMs"   DOUBLE PRECISION NOT NULL,
    "Success"      BOOLEAN          NOT NULL,
    "ErrorMessage" TEXT             NULL,
    "CreatedAt"    TIMESTAMPTZ      NOT NULL,
    CONSTRAINT "PK_tool_invocations" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_tool_invocations_ExecutionId"
    ON aihub.tool_invocations ("ExecutionId");

CREATE INDEX IF NOT EXISTS "IX_tool_invocations_AgentId"
    ON aihub.tool_invocations ("AgentId");

CREATE INDEX IF NOT EXISTS "IX_tool_invocations_ToolName"
    ON aihub.tool_invocations ("ToolName");

-- =============================================================================
-- 16. PRECIFICAÇÃO DE MODELOS LLM
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.model_pricing (
    "Id"                  INTEGER        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ModelId"             VARCHAR(256)   NOT NULL,
    "Provider"            VARCHAR(64)    NOT NULL,
    "PricePerInputToken"  NUMERIC(20,10) NOT NULL,
    "PricePerOutputToken" NUMERIC(20,10) NOT NULL,
    "Currency"            VARCHAR(3)     NOT NULL DEFAULT 'USD',
    "EffectiveFrom"       TIMESTAMPTZ    NOT NULL,
    "EffectiveTo"         TIMESTAMPTZ    NULL,
    "CreatedAt"           TIMESTAMPTZ    NOT NULL,
    CONSTRAINT "PK_model_pricing" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_model_pricing_ModelId"
    ON aihub.model_pricing ("ModelId");

-- =============================================================================
-- 16b. DOCUMENT INTELLIGENCE — Pricing por página
-- Azure Document Intelligence cobra por página processada (unidade diferente
-- de LLM que é por token). Tabela separada evita misturar semântica.
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.document_intelligence_pricing (
    "Id"            INTEGER        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ModelId"       VARCHAR(128)   NOT NULL,   -- prebuilt-layout | prebuilt-read | prebuilt-invoice | ...
    "Provider"      VARCHAR(64)    NOT NULL,   -- AZUREAI (único hoje)
    "PricePerPage"  NUMERIC(20,10) NOT NULL,   -- USD por 1 página
    "Currency"      VARCHAR(3)     NOT NULL DEFAULT 'USD',
    "EffectiveFrom" TIMESTAMPTZ    NOT NULL,
    "EffectiveTo"   TIMESTAMPTZ    NULL,
    "CreatedAt"     TIMESTAMPTZ    NOT NULL,
    CONSTRAINT "PK_document_intelligence_pricing" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_document_intelligence_pricing_ModelId"
    ON aihub.document_intelligence_pricing ("ModelId");

-- =============================================================================
-- 17. ATIVOS FINANCEIROS
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.ativos (
    "Ticker"    VARCHAR(20)  NOT NULL,
    "Nome"      VARCHAR(255) NOT NULL,
    "Setor"     VARCHAR(100) NULL,
    "Descricao" TEXT         NULL,
    "CreatedAt" TIMESTAMPTZ  NOT NULL,
    "UpdatedAt" TIMESTAMPTZ  NOT NULL,
    CONSTRAINT "PK_ativos" PRIMARY KEY ("Ticker")
);

CREATE INDEX IF NOT EXISTS "IX_ativos_Setor"
    ON aihub.ativos ("Setor");

-- =============================================================================
-- 18. CATÁLOGO DE MODELOS LLM
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.model_catalog (
    id             VARCHAR(128)  NOT NULL,
    provider       VARCHAR(64)   NOT NULL,   -- OPENAI | AZUREOPENAI | AZUREFOUNDRY
    display_name   VARCHAR(256)  NOT NULL,
    description    TEXT          NULL,
    context_window INTEGER       NULL,
    capabilities   JSONB         NOT NULL DEFAULT '[]', -- ["chat","vision","function_calling"]
    is_active      BOOLEAN       NOT NULL DEFAULT true,
    created_at     TIMESTAMPTZ   NOT NULL,
    updated_at     TIMESTAMPTZ   NOT NULL,
    CONSTRAINT pk_model_catalog PRIMARY KEY (id, provider)
);

CREATE INDEX IF NOT EXISTS ix_model_catalog_provider
    ON aihub.model_catalog (provider);

CREATE INDEX IF NOT EXISTS ix_model_catalog_is_active
    ON aihub.model_catalog (is_active);

-- =============================================================================
-- 19. DOCUMENT INTELLIGENCE — EXTRAÇÃO DE DOCUMENTOS
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.document_extraction_jobs (
    id                  UUID PRIMARY KEY,
    conversation_id     TEXT NOT NULL,
    user_id             TEXT NOT NULL,
    source_type         TEXT NOT NULL,
    source_ref          TEXT,
    content_sha256      TEXT NOT NULL,
    model               TEXT NOT NULL,
    features_hash       TEXT,
    status              TEXT NOT NULL DEFAULT 'created',
    operation_id        TEXT,
    result_ref          TEXT,
    page_count          INT,
    cost_usd            NUMERIC(12,6),
    error_code          TEXT,
    error_message       TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at          TIMESTAMPTZ,
    finished_at         TIMESTAMPTZ,
    duration_ms         INT,

    CONSTRAINT chk_dej_status CHECK (
        status IN ('created', 'running', 'succeeded', 'failed', 'cached')
    ),
    CONSTRAINT chk_dej_error_code CHECK (
        error_code IS NULL OR error_code IN (
            'PAGE_LIMIT_EXCEEDED',
            'UNREADABLE_PDF',
            'SOURCE_UNAVAILABLE',
            'AZURE_DI_FAILURE',
            'TIMEOUT',
            'GATE_TIMEOUT',
            'CANCELLED'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_dej_hash_model
    ON aihub.document_extraction_jobs(content_sha256, model);

CREATE INDEX IF NOT EXISTS idx_dej_conversation
    ON aihub.document_extraction_jobs(conversation_id);

CREATE INDEX IF NOT EXISTS idx_dej_status_created
    ON aihub.document_extraction_jobs(status, created_at);

CREATE TABLE IF NOT EXISTS aihub.document_extraction_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id       UUID NOT NULL REFERENCES aihub.document_extraction_jobs(id),
    event_type   TEXT NOT NULL,
    detail       JSONB,
    occurred_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_dee_job
    ON aihub.document_extraction_events(job_id, occurred_at);

CREATE TABLE IF NOT EXISTS aihub.document_extraction_cache (
    content_sha256      TEXT NOT NULL,
    model               TEXT NOT NULL,
    features_hash       TEXT NOT NULL,
    result_ref          TEXT NOT NULL,
    page_count          INT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at          TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (content_sha256, model, features_hash)
);

-- =============================================================================
-- 20. PERSONA PROMPT TEMPLATES — texto que compõe o bloco de persona no
--     system message do LLM. Placeholders {{segment}}, {{risk_profile}}, etc
--     são substituídos em runtime pelo PersonaPromptComposer.
--
--     Scope: 'global' (default aplicado a todos os agentes) ou 'agent:{agentId}'
--     (override específico). Lookup do runtime: agent-specific → global → null.
--
--     Update in-place (sem versionamento de linha): UPDATE substitui o template.
--     Auditoria de mudanças via admin_audit_log (resource_type='persona_prompt_template').
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.persona_prompt_templates (
    "Id"              SERIAL PRIMARY KEY,
    "Scope"           VARCHAR(128) NOT NULL,
    "Name"            VARCHAR(128) NOT NULL,
    "Template"        TEXT NOT NULL,
    "CreatedAt"       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UpdatedAt"       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UpdatedBy"       VARCHAR(128) NULL,
    "ActiveVersionId" UUID NULL,  -- F5 — aponta pra version ativa em persona_prompt_template_versions
    CONSTRAINT template_length CHECK (LENGTH("Template") <= 50000)  -- F3
);

-- F5 — histórico append-only de versions.
CREATE TABLE IF NOT EXISTS aihub.persona_prompt_template_versions (
    "Id"             SERIAL PRIMARY KEY,
    "TemplateId"     INT NOT NULL REFERENCES aihub.persona_prompt_templates("Id") ON DELETE CASCADE,
    "VersionId"      UUID NOT NULL DEFAULT gen_random_uuid(),
    "Template"       TEXT NOT NULL,
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "CreatedBy"      VARCHAR(128) NULL,
    "ChangeReason"   VARCHAR(512) NULL,
    CONSTRAINT template_length_version CHECK (LENGTH("Template") <= 50000)
);

CREATE INDEX IF NOT EXISTS ix_ptv_template_created
    ON aihub.persona_prompt_template_versions("TemplateId", "CreatedAt" DESC);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ptv_version_id
    ON aihub.persona_prompt_template_versions("VersionId");

-- UNIQUE(Scope): 1 template ativo por scope. Conflitos de escrita concorrente
-- resolvidos no controller via upsert.
CREATE UNIQUE INDEX IF NOT EXISTS "UX_persona_prompt_templates_Scope"
    ON aihub.persona_prompt_templates ("Scope");

-- =============================================================================
-- F6 — A/B testing de templates (persona_prompt_experiments)
-- Ver docs/adr/005-persona-ab-testing.md e db/migration_persona_experiments.sql
-- =============================================================================

CREATE TABLE IF NOT EXISTS aihub.persona_prompt_experiments (
    "Id"                 SERIAL PRIMARY KEY,
    "ProjectId"          VARCHAR(128) NOT NULL,
    "Scope"              VARCHAR(128) NOT NULL,
    "Name"               VARCHAR(128) NOT NULL,
    "VariantAVersionId"  UUID NOT NULL,
    "VariantBVersionId"  UUID NOT NULL,
    "TrafficSplitB"      INT NOT NULL CHECK ("TrafficSplitB" BETWEEN 0 AND 100),
    "Metric"             VARCHAR(64) NOT NULL,
    "StartedAt"          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "EndedAt"            TIMESTAMPTZ NULL,
    "CreatedBy"          VARCHAR(128) NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_persona_experiments_active
    ON aihub.persona_prompt_experiments("ProjectId", "Scope")
    WHERE "EndedAt" IS NULL;

CREATE INDEX IF NOT EXISTS ix_persona_experiments_project
    ON aihub.persona_prompt_experiments("ProjectId", "StartedAt" DESC);

-- F6 — outcome binding: llm_token_usage guarda experiment + variant.
ALTER TABLE aihub.llm_token_usage
    ADD COLUMN IF NOT EXISTS "ExperimentId" INT NULL,
    ADD COLUMN IF NOT EXISTS "ExperimentVariant" CHAR(1) NULL
        CHECK ("ExperimentVariant" IN ('A', 'B'));

CREATE INDEX IF NOT EXISTS ix_llm_token_usage_experiment
    ON aihub.llm_token_usage("ExperimentId")
    WHERE "ExperimentId" IS NOT NULL;

-- =============================================================================
-- FIM DO SCHEMA
-- =============================================================================
